# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.payment_rule_field import PaymentRuleField
from .list_fields_payment_rules_response_page_info import ListFieldsPaymentRulesResponsePageInfo


class ListFieldsPaymentRulesResponse(UniversalBaseModel):
    data: typing.List[PaymentRuleField]
    page_info: ListFieldsPaymentRulesResponsePageInfo

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
