# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.bounty_submission import BountySubmission
from .list_bounty_submissions_response_page_info import ListBountySubmissionsResponsePageInfo


class ListBountySubmissionsResponse(UniversalBaseModel):
    data: typing.List[BountySubmission]
    page_info: ListBountySubmissionsResponsePageInfo

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
