# This file was auto-generated by Fern from our API Definition.

import typing

ListEarningsRequestStatus = typing.Union[
    typing.Literal["awaiting_settlement", "pending", "completed", "canceled", "reversed"], typing.Any
]
