# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateCoursesRequestChaptersItemLessonsItem(UniversalBaseModel):
    """
    Input for updating a lesson while updating a course
    """

    chapter_id: str = pydantic.Field()
    """
    The ID of the chapter this lesson belongs to (for moving between chapters)
    """

    id: str = pydantic.Field()
    """
    The ID of the lesson to update
    """

    order: int = pydantic.Field()
    """
    The order of the lesson within its chapter
    """

    title: str = pydantic.Field()
    """
    The title of the lesson
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
