# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_financing_applications_request_answers_item_money import UpdateFinancingApplicationsRequestAnswersItemMoney


class UpdateFinancingApplicationsRequestAnswersItem(UniversalBaseModel):
    file_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Complete replacement set of uploaded file IDs for this requirement. Empty removes all files.
    """

    money: typing.Optional[UpdateFinancingApplicationsRequestAnswersItemMoney] = None
    requirement_id: str = pydantic.Field()
    """
    ID of a merchant requirement returned on this application.
    """

    values: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Text answers. Use money instead for max_product_price.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
