# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.affiliate import Affiliate
from ..types.affiliate_list_item import AffiliateListItem
from ..types.affiliates_sortable_columns import AffiliatesSortableColumns
from ..types.direction import Direction
from ..types.status import Status
from .raw_client import AsyncRawAffiliatesClient, RawAffiliatesClient
from .types.list_affiliates_response import ListAffiliatesResponse

if typing.TYPE_CHECKING:
    from .overrides.client import AsyncOverridesClient, OverridesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AffiliatesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAffiliatesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._overrides: typing.Optional[OverridesClient] = None

    @property
    def with_raw_response(self) -> RawAffiliatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAffiliatesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        account_id: str,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        first: typing.Optional[int] = None,
        last: typing.Optional[int] = None,
        direction: typing.Optional[Direction] = None,
        order: typing.Optional[AffiliatesSortableColumns] = None,
        query: typing.Optional[str] = None,
        status: typing.Optional[Status] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[AffiliateListItem, ListAffiliatesResponse]:
        """
        Returns a paginated list of affiliates for the actor in context, with optional filtering by status, search, and sorting.

        Required permissions:
         - `affiliate:basic:read`

        Parameters
        ----------
        account_id : str
            The unique identifier of the company to list affiliates for.

        after : typing.Optional[str]
            Returns the elements in the list that come after the specified cursor.

        before : typing.Optional[str]
            Returns the elements in the list that come before the specified cursor.

        first : typing.Optional[int]
            Returns the first _n_ elements from the list.

        last : typing.Optional[int]
            Returns the last _n_ elements from the list.

        direction : typing.Optional[Direction]

        order : typing.Optional[AffiliatesSortableColumns]

        query : typing.Optional[str]
            Search affiliates by username.

        status : typing.Optional[Status]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[AffiliateListItem, ListAffiliatesResponse]
            A successful response

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        response = client.affiliates.list(
            first=42,
            last=42,
            account_id="biz_xxxxxxxxxxxxxx",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            account_id=account_id,
            after=after,
            before=before,
            first=first,
            last=last,
            direction=direction,
            order=order,
            query=query,
            status=status,
            request_options=request_options,
        )

    def create(
        self, *, account_id: str, user_identifier: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Affiliate:
        """
        Creates or finds an affiliate for a company and user.

        Required permissions:
         - `affiliate:create`

        Parameters
        ----------
        account_id : str
            The ID of the company to create the affiliate for.

        user_identifier : str
            The user identifier (username, email, user ID, or Discord ID).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Affiliate
            A successful response

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        client.affiliates.create(
            account_id="biz_xxxxxxxxxxxxxx",
            user_identifier="user_identifier",
        )
        """
        _response = self._raw_client.create(
            account_id=account_id, user_identifier=user_identifier, request_options=request_options
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Affiliate:
        """
        Retrieves the details of an existing affiliate.

        Required permissions:
         - `affiliate:basic:read`

        Parameters
        ----------
        id : str
            The unique identifier of the affiliate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Affiliate
            A successful response

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        client.affiliates.retrieve(
            id="aff_xxxxxxxxxxxxxx",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def archive(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> bool:
        """
        Archives an existing Affiliate

        Required permissions:
         - `affiliate:update`

        Parameters
        ----------
        id : str
            The internal ID of the affiliate to archive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        bool
            A successful response

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        client.affiliates.archive(
            id="aff_xxxxxxxxxxxxxx",
        )
        """
        _response = self._raw_client.archive(id, request_options=request_options)
        return _response.data

    def unarchive(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> bool:
        """
        Unarchives an existing Affiliate

        Required permissions:
         - `affiliate:update`

        Parameters
        ----------
        id : str
            The internal ID of the affiliate to archive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        bool
            A successful response

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        client.affiliates.unarchive(
            id="aff_xxxxxxxxxxxxxx",
        )
        """
        _response = self._raw_client.unarchive(id, request_options=request_options)
        return _response.data

    @property
    def overrides(self):
        if self._overrides is None:
            from .overrides.client import OverridesClient  # noqa: E402

            self._overrides = OverridesClient(client_wrapper=self._client_wrapper)
        return self._overrides


class AsyncAffiliatesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAffiliatesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._overrides: typing.Optional[AsyncOverridesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAffiliatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAffiliatesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        account_id: str,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        first: typing.Optional[int] = None,
        last: typing.Optional[int] = None,
        direction: typing.Optional[Direction] = None,
        order: typing.Optional[AffiliatesSortableColumns] = None,
        query: typing.Optional[str] = None,
        status: typing.Optional[Status] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[AffiliateListItem, ListAffiliatesResponse]:
        """
        Returns a paginated list of affiliates for the actor in context, with optional filtering by status, search, and sorting.

        Required permissions:
         - `affiliate:basic:read`

        Parameters
        ----------
        account_id : str
            The unique identifier of the company to list affiliates for.

        after : typing.Optional[str]
            Returns the elements in the list that come after the specified cursor.

        before : typing.Optional[str]
            Returns the elements in the list that come before the specified cursor.

        first : typing.Optional[int]
            Returns the first _n_ elements from the list.

        last : typing.Optional[int]
            Returns the last _n_ elements from the list.

        direction : typing.Optional[Direction]

        order : typing.Optional[AffiliatesSortableColumns]

        query : typing.Optional[str]
            Search affiliates by username.

        status : typing.Optional[Status]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[AffiliateListItem, ListAffiliatesResponse]
            A successful response

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.affiliates.list(
                first=42,
                last=42,
                account_id="biz_xxxxxxxxxxxxxx",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            account_id=account_id,
            after=after,
            before=before,
            first=first,
            last=last,
            direction=direction,
            order=order,
            query=query,
            status=status,
            request_options=request_options,
        )

    async def create(
        self, *, account_id: str, user_identifier: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Affiliate:
        """
        Creates or finds an affiliate for a company and user.

        Required permissions:
         - `affiliate:create`

        Parameters
        ----------
        account_id : str
            The ID of the company to create the affiliate for.

        user_identifier : str
            The user identifier (username, email, user ID, or Discord ID).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Affiliate
            A successful response

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.affiliates.create(
                account_id="biz_xxxxxxxxxxxxxx",
                user_identifier="user_identifier",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            account_id=account_id, user_identifier=user_identifier, request_options=request_options
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Affiliate:
        """
        Retrieves the details of an existing affiliate.

        Required permissions:
         - `affiliate:basic:read`

        Parameters
        ----------
        id : str
            The unique identifier of the affiliate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Affiliate
            A successful response

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.affiliates.retrieve(
                id="aff_xxxxxxxxxxxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def archive(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> bool:
        """
        Archives an existing Affiliate

        Required permissions:
         - `affiliate:update`

        Parameters
        ----------
        id : str
            The internal ID of the affiliate to archive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        bool
            A successful response

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.affiliates.archive(
                id="aff_xxxxxxxxxxxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.archive(id, request_options=request_options)
        return _response.data

    async def unarchive(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> bool:
        """
        Unarchives an existing Affiliate

        Required permissions:
         - `affiliate:update`

        Parameters
        ----------
        id : str
            The internal ID of the affiliate to archive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        bool
            A successful response

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-09-02-2",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.affiliates.unarchive(
                id="aff_xxxxxxxxxxxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unarchive(id, request_options=request_options)
        return _response.data

    @property
    def overrides(self):
        if self._overrides is None:
            from .overrides.client import AsyncOverridesClient  # noqa: E402

            self._overrides = AsyncOverridesClient(client_wrapper=self._client_wrapper)
        return self._overrides
