# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_messages_request_poll_options_item import CreateMessagesRequestPollOptionsItem


class CreateMessagesRequestPoll(UniversalBaseModel):
    """
    A poll to attach to this message, allowing recipients to vote on options.
    """

    options: typing.List[CreateMessagesRequestPollOptionsItem] = pydantic.Field()
    """
    The options for the poll. Must have sequential IDs starting from 1
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
