# This file was auto-generated by Fern from our API Definition.

import typing

PostChatMessageCreatedPayloadDataChannelType = typing.Union[
    typing.Literal["chat", "direct_message", "support"], typing.Any
]
