# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.message import Message
from .post_chat_message_created_payload_data_audience import PostChatMessageCreatedPayloadDataAudience
from .post_chat_message_created_payload_data_channel import PostChatMessageCreatedPayloadDataChannel


class PostChatMessageCreatedPayloadData(UniversalBaseModel):
    audience: PostChatMessageCreatedPayloadDataAudience
    channel: PostChatMessageCreatedPayloadDataChannel
    message: Message
    reason: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
