# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_ad_groups_request_placements_one_item_platform import CreateAdGroupsRequestPlacementsOneItemPlatform


class CreateAdGroupsRequestPlacementsOneItem(UniversalBaseModel):
    platform: CreateAdGroupsRequestPlacementsOneItemPlatform = pydantic.Field()
    """
    Platform the ads run on.
    """

    positions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Positions to target within the platform, such as `feed` or `story`. Omit to target all of the platform's positions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
