# This file was auto-generated by Fern from our API Definition.

import typing

PostAdGroupUpdatedPayloadDataMessageAppsItem = typing.Union[
    typing.Literal["messenger", "instagram", "whatsapp"], typing.Any
]
