# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_domains_request_direction import ListDomainsRequestDirection
    from .list_domains_request_order import ListDomainsRequestOrder
    from .list_domains_request_status import ListDomainsRequestStatus
    from .list_domains_response import ListDomainsResponse
    from .list_domains_response_page_info import ListDomainsResponsePageInfo
_dynamic_imports: typing.Dict[str, str] = {
    "ListDomainsRequestDirection": ".list_domains_request_direction",
    "ListDomainsRequestOrder": ".list_domains_request_order",
    "ListDomainsRequestStatus": ".list_domains_request_status",
    "ListDomainsResponse": ".list_domains_response",
    "ListDomainsResponsePageInfo": ".list_domains_response_page_info",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListDomainsRequestDirection",
    "ListDomainsRequestOrder",
    "ListDomainsRequestStatus",
    "ListDomainsResponse",
    "ListDomainsResponsePageInfo",
]
