# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateDomainsRequestRegistration(UniversalBaseModel):
    """
    Buy the domain through Whop, renew it every year, and let Whop run its DNS. Pass `null` to release an unpaid or failed purchase.
    """

    auto_renew: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether Whop charges the saved card to renew the domain before it expires.
    """

    payment_method_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Saved card to charge, prefixed `payt_`. It must belong to the signed-in user. Pass `null` to remove it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
