# This file was auto-generated by Fern from our API Definition.

import typing

CreateAdCampaignsRequestBidType = typing.Union[
    typing.Literal["minimum_cost", "average_target", "maximum_target"], typing.Any
]
