# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.ad_platform_issue import AdPlatformIssue
from .post_ad_campaign_updated_payload_data_bid_type import PostAdCampaignUpdatedPayloadDataBidType
from .post_ad_campaign_updated_payload_data_budget_optimization import (
    PostAdCampaignUpdatedPayloadDataBudgetOptimization,
)
from .post_ad_campaign_updated_payload_data_budget_type import PostAdCampaignUpdatedPayloadDataBudgetType
from .post_ad_campaign_updated_payload_data_delivery_status import PostAdCampaignUpdatedPayloadDataDeliveryStatus
from .post_ad_campaign_updated_payload_data_objective import PostAdCampaignUpdatedPayloadDataObjective
from .post_ad_campaign_updated_payload_data_platform import PostAdCampaignUpdatedPayloadDataPlatform
from .post_ad_campaign_updated_payload_data_special_ad_categories_item import (
    PostAdCampaignUpdatedPayloadDataSpecialAdCategoriesItem,
)
from .post_ad_campaign_updated_payload_data_status import PostAdCampaignUpdatedPayloadDataStatus


class PostAdCampaignUpdatedPayloadData(UniversalBaseModel):
    bid_type: typing.Optional[PostAdCampaignUpdatedPayloadDataBidType] = pydantic.Field(default=None)
    """
    How delivery bids in the ad auction: `minimum_cost` gets the most results for the budget, `average_target` holds an average cost per result, and `maximum_target` never bids above a cap.
    """

    budget_amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    The campaign's budget, in the ad account's currency. `null` when each ad group sets its own budget instead.
    """

    budget_optimization: typing.Optional[PostAdCampaignUpdatedPayloadDataBudgetOptimization] = pydantic.Field(
        default=None
    )
    """
    Which level owns the budget: the whole campaign (`ad_campaign`) or each ad group individually (`ad_group`).
    """

    budget_type: typing.Optional[PostAdCampaignUpdatedPayloadDataBudgetType] = pydantic.Field(default=None)
    """
    Whether `budget_amount` is spent per day (`daily`) or over the campaign's full run (`lifetime`).
    """

    created_at: str = pydantic.Field()
    """
    When the campaign was created, as an ISO 8601 timestamp.
    """

    delivery_status: PostAdCampaignUpdatedPayloadDataDeliveryStatus = pydantic.Field()
    """
    Whether the campaign's ads are delivering right now, and if not, why. When several states apply at once, the highest-precedence one is returned.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the ad campaign, prefixed `adcamp_`.
    """

    issues: typing.List[AdPlatformIssue]
    objective: typing.Optional[PostAdCampaignUpdatedPayloadDataObjective] = pydantic.Field(default=None)
    """
    The goal the campaign optimizes toward.
    """

    optimization_goal: typing.Optional[str] = pydantic.Field(default=None)
    """
    The event the campaign optimizes for when a single goal is set campaign-wide. `null` when each ad group sets its own optimization_goal.
    """

    platform: PostAdCampaignUpdatedPayloadDataPlatform = pydantic.Field()
    """
    The ad network the campaign runs on.
    """

    special_ad_categories: typing.List[PostAdCampaignUpdatedPayloadDataSpecialAdCategoriesItem]
    status: PostAdCampaignUpdatedPayloadDataStatus = pydantic.Field()
    """
    The lifecycle status of the ad campaign.
    """

    title: str = pydantic.Field()
    """
    Display name of the ad campaign.
    """

    updated_at: str = pydantic.Field()
    """
    When the campaign was last updated, as an ISO 8601 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
