# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_transfers_response_transfer_created_by_user import CreateTransfersResponseTransferCreatedByUser
from .create_transfers_response_transfer_destination import CreateTransfersResponseTransferDestination
from .create_transfers_response_transfer_origin import CreateTransfersResponseTransferOrigin
from .create_transfers_response_transfer_status import CreateTransfersResponseTransferStatus


class CreateTransfersResponseTransfer(UniversalBaseModel):
    """
    A transfer of credit between two ledger accounts.
    """

    amount: float = pydantic.Field()
    """
    Transfer amount.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the transfer was created.
    """

    created_by_user: typing.Optional[CreateTransfersResponseTransferCreatedByUser] = pydantic.Field(default=None)
    """
    The user who initiated the transfer, such as the team member who sent a manual payout. Null if the creator is unavailable.
    """

    currency: str = pydantic.Field()
    """
    Transfer currency.
    """

    destination: CreateTransfersResponseTransferDestination = pydantic.Field()
    """
    Account or user receiving funds.
    """

    destination_ledger_account_id: str = pydantic.Field()
    """
    Destination ledger account ID.
    """

    failed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the transfer failed, as an ISO 8601 timestamp. Null unless the transfer has failed.
    """

    failure_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Machine-readable code for why the transfer failed. Null unless the transfer has failed.
    """

    failure_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable explanation of why the transfer failed. Null unless the transfer has failed.
    """

    fee_amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Fee charged for the transfer.
    """

    id: str = pydantic.Field()
    """
    Transfer ID.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom metadata attached to the transfer.
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transfer note.
    """

    origin: CreateTransfersResponseTransferOrigin = pydantic.Field()
    """
    Account or user sending funds.
    """

    origin_ledger_account_id: str = pydantic.Field()
    """
    Source ledger account ID.
    """

    status: CreateTransfersResponseTransferStatus = pydantic.Field()
    """
    Transfer status. `processing` means the on-chain leg is still executing — poll the transfer until it resolves to `succeeded` or `failed`. A `failed` transfer may be retried under the same ID and later resolve to `succeeded`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
