# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateTransfersResponseTransferDestination_Company(UniversalBaseModel):
    """
    Account or user receiving funds.
    """

    typename: typing.Literal["Company"] = "Company"
    id: str
    route: typing.Optional[str] = None
    title: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreateTransfersResponseTransferDestination_User(UniversalBaseModel):
    """
    Account or user receiving funds.
    """

    typename: typing.Literal["User"] = "User"
    id: str
    name: typing.Optional[str] = None
    username: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CreateTransfersResponseTransferDestination = typing_extensions.Annotated[
    typing.Union[CreateTransfersResponseTransferDestination_Company, CreateTransfersResponseTransferDestination_User],
    pydantic.Field(discriminator="typename"),
]
