# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostTransferCreatedPayloadDataOriginCompany(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Account ID.
    """

    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account route.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account display name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
