# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateFeesRequestMarkupsTransfers(UniversalBaseModel):
    """
    The new markup. Fields left out keep their current value; `null` clears the row so the markup returns to its default.
    """

    fixed: typing.Optional[float] = pydantic.Field(default=None)
    """
    The amount the platform adds per event, in US dollars.
    """

    percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    The percentage of the transaction the platform adds, where `2` means 2%.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
