# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.product_affiliate import ProductAffiliate
from .list_product_affiliates_response_page_info import ListProductAffiliatesResponsePageInfo


class ListProductAffiliatesResponse(UniversalBaseModel):
    data: typing.List[ProductAffiliate]
    page_info: ListProductAffiliatesResponsePageInfo
    total_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Matching product affiliates, or `null` past 10,000.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
