# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_swaps_response_data_item import ListSwapsResponseDataItem


class ListSwapsResponse(UniversalBaseModel):
    data: typing.List[ListSwapsResponseDataItem] = pydantic.Field()
    """
    Swaps returned for this account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
