# This file was auto-generated by Fern from our API Definition.

import typing

RetrievePreferencesResponseAdsPaymentMethodsBackupType = typing.Union[
    typing.Literal["platform_balance", "card"], typing.Any
]
