# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieve_preferences_response_ads_triple_whale_integration_status import (
    RetrievePreferencesResponseAdsTripleWhaleIntegrationStatus,
)


class RetrievePreferencesResponseAdsTripleWhaleIntegration(UniversalBaseModel):
    """
    The account's Triple Whale integration, which pushes Whop ad spend to Triple Whale's Data-In API so it reports as a `whop` channel. Available to any Triple Whale customer — Shopify, WooCommerce, a custom checkout, or no connected store — by setting `shop_domain` explicitly; Shopify merchants may instead rely on a connected store's domain. Requires the `ad_campaign:create` scope. Once connected, ad click-through URLs Whop serves carry `tw_source=whop` and `tw_adid=<ad id>` query parameters so Triple Whale's pixel attributes conversions back to the originating ad — no destination URL changes are needed.
    """

    masked_api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The leading characters of the stored Data-In API key, followed by asterisks. The full key is never returned. `null` when no key is stored.
    """

    shop_domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The shop domain spend is reported for, such as `acme.myshopify.com` or a custom domain for a non-Shopify store. This is the explicit `shop_domain` if one was set, otherwise a connected Shopify store's domain. `null` when neither is present.
    """

    status: RetrievePreferencesResponseAdsTripleWhaleIntegrationStatus = pydantic.Field()
    """
    Where the integration stands. `requires_shop_domain` means no shop domain is configured — set `shop_domain` explicitly, or connect a Shopify store, before spend can be reported.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
