# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_preferences_request_ads_payment_methods_backup import UpdatePreferencesRequestAdsPaymentMethodsBackup
from .update_preferences_request_ads_payment_methods_primary import UpdatePreferencesRequestAdsPaymentMethodsPrimary


class UpdatePreferencesRequestAdsPaymentMethods(UniversalBaseModel):
    """
    How the account pays for Whop Ads spend. `primary` is charged first; `backup` covers the charge when the primary fails.
    """

    backup: typing.Optional[UpdatePreferencesRequestAdsPaymentMethodsBackup] = pydantic.Field(default=None)
    """
    Optional second method charged if the primary fails. Any pairing is allowed (two cards, card+balance, balance+card); omit it to run on a single method. Must differ from the primary.
    """

    primary: UpdatePreferencesRequestAdsPaymentMethodsPrimary

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
