# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .upload_evidence_disputes_request_documents_item_document_type import (
    UploadEvidenceDisputesRequestDocumentsItemDocumentType,
)


class UploadEvidenceDisputesRequestDocumentsItem(UniversalBaseModel):
    direct_upload_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID returned by a direct upload.
    """

    document_type: UploadEvidenceDisputesRequestDocumentsItemDocumentType = pydantic.Field()
    """
    What kind of evidence the document is.
    """

    file: typing.Optional[bytes] = pydantic.Field(default=None)
    """
    The file itself. Send it as a file part to upload and attach in one call, or use `id`/`direct_upload_id` for a file that is already stored.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of a file already stored on Whop, prefixed `file_`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
