# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.promo_code import PromoCode
from ..types.promo_code_list_item import PromoCodeListItem
from ..types.v1error_response import V1ErrorResponse
from .types.create_promo_codes_request_base_currency import CreatePromoCodesRequestBaseCurrency
from .types.create_promo_codes_request_promo_type import CreatePromoCodesRequestPromoType
from .types.delete_promo_codes_response import DeletePromoCodesResponse
from .types.list_promo_codes_request_direction import ListPromoCodesRequestDirection
from .types.list_promo_codes_request_order import ListPromoCodesRequestOrder
from .types.list_promo_codes_request_status import ListPromoCodesRequestStatus
from .types.list_promo_codes_response import ListPromoCodesResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPromoCodesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        account_id: str,
        status: typing.Optional[ListPromoCodesRequestStatus] = None,
        product_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        plan_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        order: typing.Optional[ListPromoCodesRequestOrder] = None,
        direction: typing.Optional[ListPromoCodesRequestDirection] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[PromoCodeListItem, ListPromoCodesResponse]:
        """
        Lists promo codes for an account with cursor pagination, filters, and sorting.

        Parameters
        ----------
        account_id : str
            Account whose promo codes are listed (`biz_` tag).

        status : typing.Optional[ListPromoCodesRequestStatus]
            Promo-code status. `expired` groups inactive and archived codes.

        product_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only promo codes scoped to these product IDs.

        plan_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only promo codes scoped to these plan IDs.

        created_before : typing.Optional[dt.datetime]
            Only promo codes created before this ISO 8601 timestamp.

        created_after : typing.Optional[dt.datetime]
            Only promo codes created after this ISO 8601 timestamp.

        order : typing.Optional[ListPromoCodesRequestOrder]
            Sort field.

        direction : typing.Optional[ListPromoCodesRequestDirection]
            Sort direction.

        first : typing.Optional[int]
            Number of promo codes to return from the start of the window.

        after : typing.Optional[str]
            Cursor to paginate forwards from.

        last : typing.Optional[int]
            Number of promo codes to return from the end of the window.

        before : typing.Optional[str]
            Cursor to paginate backwards from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[PromoCodeListItem, ListPromoCodesResponse]
            promo codes listed
        """
        _response = self._client_wrapper.httpx_client.request(
            "promo_codes",
            method="GET",
            params={
                "account_id": account_id,
                "status": status,
                "product_ids": product_ids,
                "plan_ids": plan_ids,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "order": order,
                "direction": direction,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPromoCodesResponse,
                    parse_obj_as(
                        type_=ListPromoCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        account_id=account_id,
                        status=status,
                        product_ids=product_ids,
                        plan_ids=plan_ids,
                        created_before=created_before,
                        created_after=created_after,
                        order=order,
                        direction=direction,
                        first=first,
                        after=_parsed_next,
                        last=last,
                        before=before,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        account_id: str,
        amount_off: float,
        base_currency: CreatePromoCodesRequestBaseCurrency,
        code: str,
        new_users_only: bool,
        promo_duration_months: int,
        promo_type: CreatePromoCodesRequestPromoType,
        churned_users_only: typing.Optional[bool] = OMIT,
        existing_memberships_only: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[str] = OMIT,
        one_per_customer: typing.Optional[bool] = OMIT,
        plan_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        product_id: typing.Optional[str] = OMIT,
        stock: typing.Optional[int] = OMIT,
        unlimited_stock: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PromoCode]:
        """
        Creates a promo code for an account. First-party sessions may attach an affiliate.

        Parameters
        ----------
        account_id : str

        amount_off : float

        base_currency : CreatePromoCodesRequestBaseCurrency

        code : str

        new_users_only : bool

        promo_duration_months : int

        promo_type : CreatePromoCodesRequestPromoType

        churned_users_only : typing.Optional[bool]

        existing_memberships_only : typing.Optional[bool]

        expires_at : typing.Optional[str]

        one_per_customer : typing.Optional[bool]

        plan_ids : typing.Optional[typing.Sequence[str]]

        product_id : typing.Optional[str]

        stock : typing.Optional[int]

        unlimited_stock : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PromoCode]
            promo code created
        """
        _response = self._client_wrapper.httpx_client.request(
            "promo_codes",
            method="POST",
            json={
                "account_id": account_id,
                "amount_off": amount_off,
                "base_currency": base_currency,
                "churned_users_only": churned_users_only,
                "code": code,
                "existing_memberships_only": existing_memberships_only,
                "expires_at": expires_at,
                "new_users_only": new_users_only,
                "one_per_customer": one_per_customer,
                "plan_ids": plan_ids,
                "product_id": product_id,
                "promo_duration_months": promo_duration_months,
                "promo_type": promo_type,
                "stock": stock,
                "unlimited_stock": unlimited_stock,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[PromoCode]:
        """
        Retrieves a promo code by ID.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PromoCode]
            promo code retrieved
        """
        _response = self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeletePromoCodesResponse]:
        """
        Archives a promo code so it cannot be used in future checkouts.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeletePromoCodesResponse]
            promo code deleted
        """
        _response = self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePromoCodesResponse,
                    parse_obj_as(
                        type_=DeletePromoCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def activate(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[PromoCode]:
        """
        Turns an inactive promo code back on so it can be redeemed at checkout.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PromoCode]
            promo code activated
        """
        _response = self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}/activate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def deactivate(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PromoCode]:
        """
        Turns off an active promo code so it can no longer be redeemed at checkout.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PromoCode]
            promo code deactivated
        """
        _response = self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}/deactivate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPromoCodesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        account_id: str,
        status: typing.Optional[ListPromoCodesRequestStatus] = None,
        product_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        plan_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        order: typing.Optional[ListPromoCodesRequestOrder] = None,
        direction: typing.Optional[ListPromoCodesRequestDirection] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[PromoCodeListItem, ListPromoCodesResponse]:
        """
        Lists promo codes for an account with cursor pagination, filters, and sorting.

        Parameters
        ----------
        account_id : str
            Account whose promo codes are listed (`biz_` tag).

        status : typing.Optional[ListPromoCodesRequestStatus]
            Promo-code status. `expired` groups inactive and archived codes.

        product_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only promo codes scoped to these product IDs.

        plan_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only promo codes scoped to these plan IDs.

        created_before : typing.Optional[dt.datetime]
            Only promo codes created before this ISO 8601 timestamp.

        created_after : typing.Optional[dt.datetime]
            Only promo codes created after this ISO 8601 timestamp.

        order : typing.Optional[ListPromoCodesRequestOrder]
            Sort field.

        direction : typing.Optional[ListPromoCodesRequestDirection]
            Sort direction.

        first : typing.Optional[int]
            Number of promo codes to return from the start of the window.

        after : typing.Optional[str]
            Cursor to paginate forwards from.

        last : typing.Optional[int]
            Number of promo codes to return from the end of the window.

        before : typing.Optional[str]
            Cursor to paginate backwards from.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[PromoCodeListItem, ListPromoCodesResponse]
            promo codes listed
        """
        _response = await self._client_wrapper.httpx_client.request(
            "promo_codes",
            method="GET",
            params={
                "account_id": account_id,
                "status": status,
                "product_ids": product_ids,
                "plan_ids": plan_ids,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "order": order,
                "direction": direction,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPromoCodesResponse,
                    parse_obj_as(
                        type_=ListPromoCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            account_id=account_id,
                            status=status,
                            product_ids=product_ids,
                            plan_ids=plan_ids,
                            created_before=created_before,
                            created_after=created_after,
                            order=order,
                            direction=direction,
                            first=first,
                            after=_parsed_next,
                            last=last,
                            before=before,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        account_id: str,
        amount_off: float,
        base_currency: CreatePromoCodesRequestBaseCurrency,
        code: str,
        new_users_only: bool,
        promo_duration_months: int,
        promo_type: CreatePromoCodesRequestPromoType,
        churned_users_only: typing.Optional[bool] = OMIT,
        existing_memberships_only: typing.Optional[bool] = OMIT,
        expires_at: typing.Optional[str] = OMIT,
        one_per_customer: typing.Optional[bool] = OMIT,
        plan_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        product_id: typing.Optional[str] = OMIT,
        stock: typing.Optional[int] = OMIT,
        unlimited_stock: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PromoCode]:
        """
        Creates a promo code for an account. First-party sessions may attach an affiliate.

        Parameters
        ----------
        account_id : str

        amount_off : float

        base_currency : CreatePromoCodesRequestBaseCurrency

        code : str

        new_users_only : bool

        promo_duration_months : int

        promo_type : CreatePromoCodesRequestPromoType

        churned_users_only : typing.Optional[bool]

        existing_memberships_only : typing.Optional[bool]

        expires_at : typing.Optional[str]

        one_per_customer : typing.Optional[bool]

        plan_ids : typing.Optional[typing.Sequence[str]]

        product_id : typing.Optional[str]

        stock : typing.Optional[int]

        unlimited_stock : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PromoCode]
            promo code created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "promo_codes",
            method="POST",
            json={
                "account_id": account_id,
                "amount_off": amount_off,
                "base_currency": base_currency,
                "churned_users_only": churned_users_only,
                "code": code,
                "existing_memberships_only": existing_memberships_only,
                "expires_at": expires_at,
                "new_users_only": new_users_only,
                "one_per_customer": one_per_customer,
                "plan_ids": plan_ids,
                "product_id": product_id,
                "promo_duration_months": promo_duration_months,
                "promo_type": promo_type,
                "stock": stock,
                "unlimited_stock": unlimited_stock,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PromoCode]:
        """
        Retrieves a promo code by ID.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PromoCode]
            promo code retrieved
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeletePromoCodesResponse]:
        """
        Archives a promo code so it cannot be used in future checkouts.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeletePromoCodesResponse]
            promo code deleted
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePromoCodesResponse,
                    parse_obj_as(
                        type_=DeletePromoCodesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def activate(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PromoCode]:
        """
        Turns an inactive promo code back on so it can be redeemed at checkout.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PromoCode]
            promo code activated
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}/activate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def deactivate(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PromoCode]:
        """
        Turns off an active promo code so it can no longer be redeemed at checkout.

        Parameters
        ----------
        id : str
            Promo code ID (`promo_` tag).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PromoCode]
            promo code deactivated
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"promo_codes/{encode_path_param(id)}/deactivate",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PromoCode,
                    parse_obj_as(
                        type_=PromoCode,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
