# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeliveriesWebhookResponseDataItem(UniversalBaseModel):
    """
    A webhook log entry containing the request and response details
    """

    request_body: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    The request body sent to the webhook endpoint
    """

    resource_id: str = pydantic.Field()
    """
    The ID of the resource that triggered the webhook
    """

    response_body: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    The response body received from the webhook endpoint
    """

    response_code: int = pydantic.Field()
    """
    The HTTP response code received from the webhook endpoint
    """

    sent_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the webhook was sent
    """

    total_time: float = pydantic.Field()
    """
    The total time taken to send the webhook request in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
