# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_ad_conversion_value_rules_request_adjustment_type import (
        CreateAdConversionValueRulesRequestAdjustmentType,
    )
    from .create_ad_conversion_value_rules_request_events_item import CreateAdConversionValueRulesRequestEventsItem
    from .create_ad_conversion_value_rules_request_events_item_event_name import (
        CreateAdConversionValueRulesRequestEventsItemEventName,
    )
    from .create_ad_conversion_value_rules_request_fixed_value import CreateAdConversionValueRulesRequestFixedValue
    from .create_ad_conversion_value_rules_request_status import CreateAdConversionValueRulesRequestStatus
    from .create_ad_conversion_value_rules_request_targets_item import CreateAdConversionValueRulesRequestTargetsItem
    from .create_ad_conversion_value_rules_request_targets_item_platform import (
        CreateAdConversionValueRulesRequestTargetsItemPlatform,
    )
    from .create_ad_conversion_value_rules_request_targets_item_scope import (
        CreateAdConversionValueRulesRequestTargetsItemScope,
    )
    from .delete_ad_conversion_value_rules_response import DeleteAdConversionValueRulesResponse
    from .list_ad_conversion_value_rules_request_direction import ListAdConversionValueRulesRequestDirection
    from .list_ad_conversion_value_rules_request_order import ListAdConversionValueRulesRequestOrder
    from .list_ad_conversion_value_rules_request_platform import ListAdConversionValueRulesRequestPlatform
    from .list_ad_conversion_value_rules_request_status import ListAdConversionValueRulesRequestStatus
    from .list_ad_conversion_value_rules_response import ListAdConversionValueRulesResponse
    from .list_ad_conversion_value_rules_response_page_info import ListAdConversionValueRulesResponsePageInfo
    from .update_ad_conversion_value_rules_request_adjustment_type import (
        UpdateAdConversionValueRulesRequestAdjustmentType,
    )
    from .update_ad_conversion_value_rules_request_events_item import UpdateAdConversionValueRulesRequestEventsItem
    from .update_ad_conversion_value_rules_request_events_item_event_name import (
        UpdateAdConversionValueRulesRequestEventsItemEventName,
    )
    from .update_ad_conversion_value_rules_request_fixed_value import UpdateAdConversionValueRulesRequestFixedValue
    from .update_ad_conversion_value_rules_request_targets_item import UpdateAdConversionValueRulesRequestTargetsItem
    from .update_ad_conversion_value_rules_request_targets_item_platform import (
        UpdateAdConversionValueRulesRequestTargetsItemPlatform,
    )
    from .update_ad_conversion_value_rules_request_targets_item_scope import (
        UpdateAdConversionValueRulesRequestTargetsItemScope,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateAdConversionValueRulesRequestAdjustmentType": ".create_ad_conversion_value_rules_request_adjustment_type",
    "CreateAdConversionValueRulesRequestEventsItem": ".create_ad_conversion_value_rules_request_events_item",
    "CreateAdConversionValueRulesRequestEventsItemEventName": ".create_ad_conversion_value_rules_request_events_item_event_name",
    "CreateAdConversionValueRulesRequestFixedValue": ".create_ad_conversion_value_rules_request_fixed_value",
    "CreateAdConversionValueRulesRequestStatus": ".create_ad_conversion_value_rules_request_status",
    "CreateAdConversionValueRulesRequestTargetsItem": ".create_ad_conversion_value_rules_request_targets_item",
    "CreateAdConversionValueRulesRequestTargetsItemPlatform": ".create_ad_conversion_value_rules_request_targets_item_platform",
    "CreateAdConversionValueRulesRequestTargetsItemScope": ".create_ad_conversion_value_rules_request_targets_item_scope",
    "DeleteAdConversionValueRulesResponse": ".delete_ad_conversion_value_rules_response",
    "ListAdConversionValueRulesRequestDirection": ".list_ad_conversion_value_rules_request_direction",
    "ListAdConversionValueRulesRequestOrder": ".list_ad_conversion_value_rules_request_order",
    "ListAdConversionValueRulesRequestPlatform": ".list_ad_conversion_value_rules_request_platform",
    "ListAdConversionValueRulesRequestStatus": ".list_ad_conversion_value_rules_request_status",
    "ListAdConversionValueRulesResponse": ".list_ad_conversion_value_rules_response",
    "ListAdConversionValueRulesResponsePageInfo": ".list_ad_conversion_value_rules_response_page_info",
    "UpdateAdConversionValueRulesRequestAdjustmentType": ".update_ad_conversion_value_rules_request_adjustment_type",
    "UpdateAdConversionValueRulesRequestEventsItem": ".update_ad_conversion_value_rules_request_events_item",
    "UpdateAdConversionValueRulesRequestEventsItemEventName": ".update_ad_conversion_value_rules_request_events_item_event_name",
    "UpdateAdConversionValueRulesRequestFixedValue": ".update_ad_conversion_value_rules_request_fixed_value",
    "UpdateAdConversionValueRulesRequestTargetsItem": ".update_ad_conversion_value_rules_request_targets_item",
    "UpdateAdConversionValueRulesRequestTargetsItemPlatform": ".update_ad_conversion_value_rules_request_targets_item_platform",
    "UpdateAdConversionValueRulesRequestTargetsItemScope": ".update_ad_conversion_value_rules_request_targets_item_scope",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateAdConversionValueRulesRequestAdjustmentType",
    "CreateAdConversionValueRulesRequestEventsItem",
    "CreateAdConversionValueRulesRequestEventsItemEventName",
    "CreateAdConversionValueRulesRequestFixedValue",
    "CreateAdConversionValueRulesRequestStatus",
    "CreateAdConversionValueRulesRequestTargetsItem",
    "CreateAdConversionValueRulesRequestTargetsItemPlatform",
    "CreateAdConversionValueRulesRequestTargetsItemScope",
    "DeleteAdConversionValueRulesResponse",
    "ListAdConversionValueRulesRequestDirection",
    "ListAdConversionValueRulesRequestOrder",
    "ListAdConversionValueRulesRequestPlatform",
    "ListAdConversionValueRulesRequestStatus",
    "ListAdConversionValueRulesResponse",
    "ListAdConversionValueRulesResponsePageInfo",
    "UpdateAdConversionValueRulesRequestAdjustmentType",
    "UpdateAdConversionValueRulesRequestEventsItem",
    "UpdateAdConversionValueRulesRequestEventsItemEventName",
    "UpdateAdConversionValueRulesRequestFixedValue",
    "UpdateAdConversionValueRulesRequestTargetsItem",
    "UpdateAdConversionValueRulesRequestTargetsItemPlatform",
    "UpdateAdConversionValueRulesRequestTargetsItemScope",
]
