# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_direct_request_payment_method_card_details import CreateDirectRequestPaymentMethodCardDetails


class CreateDirectRequestPaymentMethodCard(UniversalBaseModel):
    """
    The card to charge. Present when `type` is `card`.
    """

    details: CreateDirectRequestPaymentMethodCardDetails = pydantic.Field()
    """
    The card's raw fields. Sent to the vault host and tokenized before it reaches Whop; Whop's servers never receive the number.
    """

    network_transaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The network transaction id of the card's most recent customer-initiated transaction on another processor, when the caller brings a card it has charged before. Required for an `off_session` charge; on a setup it is kept with the saved card for its later charges. Up to 64 characters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
