# This file was auto-generated by Fern from our API Definition.

import typing

CreateDirectRequestPlanProductVisibility = typing.Union[
    typing.Literal["visible", "hidden", "archived", "quick_link"], typing.Any
]
