# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_deposits_response_methods_crypto_item_name import CreateDepositsResponseMethodsCryptoItemName
from .create_deposits_response_methods_crypto_item_supported_currencies_item import (
    CreateDepositsResponseMethodsCryptoItemSupportedCurrenciesItem,
)


class CreateDepositsResponseMethodsCryptoItem(UniversalBaseModel):
    deposit_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Address to send funds to on this network. Null when the provider has not issued one yet.
    """

    icon_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Network icon URL.
    """

    name: CreateDepositsResponseMethodsCryptoItemName = pydantic.Field()
    """
    Network display name.
    """

    supported_currencies: typing.List[CreateDepositsResponseMethodsCryptoItemSupportedCurrenciesItem] = pydantic.Field()
    """
    Tokens accepted for deposit on this network.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
