# This file was auto-generated by Fern from our API Definition.

import typing

RetrieveFinancialReportsResponseReportType = typing.Union[
    typing.Literal["balance_summary", "income_statement", "balance_activity"], typing.Any
]
