# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.social_account import SocialAccount
from .list_social_accounts_response_page_info import ListSocialAccountsResponsePageInfo


class ListSocialAccountsResponse(UniversalBaseModel):
    data: typing.List[SocialAccount]
    page_info: ListSocialAccountsResponsePageInfo

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
