# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.ad_creative import AdCreative
from ...types.ad_entity_reference import AdEntityReference
from ...types.ad_lead_form import AdLeadForm
from ...types.ad_messaging_config import AdMessagingConfig
from ...types.ad_music import AdMusic
from ...types.ad_platform_issue import AdPlatformIssue
from .post_ad_updated_payload_data_call_to_action import PostAdUpdatedPayloadDataCallToAction
from .post_ad_updated_payload_data_delivery_status import PostAdUpdatedPayloadDataDeliveryStatus
from .post_ad_updated_payload_data_post_source import PostAdUpdatedPayloadDataPostSource
from .post_ad_updated_payload_data_status import PostAdUpdatedPayloadDataStatus


class PostAdUpdatedPayloadData(UniversalBaseModel):
    ad_campaign: AdEntityReference = pydantic.Field()
    """
    The ad campaign this ad belongs to.
    """

    ad_group: AdEntityReference = pydantic.Field()
    """
    The ad group this ad belongs to.
    """

    call_to_action: typing.Optional[PostAdUpdatedPayloadDataCallToAction] = pydantic.Field(default=None)
    """
    The call-to-action button shown on the ad.
    """

    created_at: str = pydantic.Field()
    """
    When the ad was created, as an ISO 8601 timestamp.
    """

    creatives: typing.List[AdCreative]
    delivery_status: PostAdUpdatedPayloadDataDeliveryStatus = pydantic.Field()
    """
    Whether the ad is delivering right now, and if not, why. When several states apply at once, the highest-precedence one is returned.
    """

    descriptions: typing.List[str]
    existing_post_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The post you pointed this ad at, when it promotes one you already published — a Facebook post, Instagram media, or TikTok video ID. `null` when the ad uses uploaded creatives.
    """

    headlines: typing.List[str]
    id: str = pydantic.Field()
    """
    Unique identifier for the ad, prefixed `ad_`.
    """

    issues: typing.List[AdPlatformIssue]
    lead_form: typing.Optional[AdLeadForm] = pydantic.Field(default=None)
    """
    The instant lead form shown when someone taps this ad. `null` when the ad group's conversion_location is not an instant-form destination.
    """

    lead_form_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ad platform's ID for the instant form the ad uses. Set when the ad references an existing form via `lead_form_id`, or once a form built from `lead_form` has been created on the platform.
    """

    messaging_config: typing.Optional[AdMessagingConfig] = pydantic.Field(default=None)
    """
    Welcome message for click-to-message ads, shown when the conversation opens. `null` when the ad has none.
    """

    multi_advertiser_ads: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the ad can appear alongside other advertisers' ads in the same unit. Defaults to true.
    """

    music: typing.Optional[AdMusic] = pydantic.Field(default=None)
    """
    The advertiser-uploaded MP3 a TikTok carousel ad plays. TikTok-only; `null` elsewhere and for non-carousel ads.
    """

    post_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The post the ad network serves for this ad, as `pageID_postID` on Meta — the post Meta created for an uploaded creative, or the post being promoted. Use it to open the live post, or to promote the same post from another ad. `null` until the network has created the post.
    """

    post_source: typing.Optional[PostAdUpdatedPayloadDataPostSource] = pydantic.Field(default=None)
    """
    Identifies the network that owns `existing_post_id`; `null` when the ad uses uploaded creatives.
    """

    post_thumbnail_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Preview image of the post named by `existing_post_id`. `null` for ads that use uploaded creatives, or until the post's media has been fetched from the network.
    """

    primary_texts: typing.List[str]
    social_accounts: typing.List[AdEntityReference]
    status: PostAdUpdatedPayloadDataStatus = pydantic.Field()
    """
    Whether the ad is enabled. `active` and `paused` are set by you; `in_review` and `rejected` come from ad review.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display title of the ad.
    """

    updated_at: str = pydantic.Field()
    """
    When the ad was last updated, as an ISO 8601 timestamp.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL the ad links to, without its query string. Parameters belong in `url_parameters`; any you send on `url` are moved there.
    """

    url_parameters: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Every query parameter appended to the URL, keyed by parameter name — including any you sent on `url` itself. Whop adds its own click-attribution parameters on top; those are reserved and rejected if you set them. Which keys are reserved depends on the ad's network — Meta: utm_meta_ad_id, utm_meta_adset_id, utm_meta_campaign_id, utm_source, utm_placement, utm_medium, utm_content, utm_adset, utm_whop, wacid, wasid, waid, tw_source, tw_adid; TikTok: waid, wasid, wacid, ad_id, adset_id, campaign_id, utm_source, utm_medium, utm_placement, utm_whop, tw_source, tw_adid.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
