# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawLedgersClient, RawLedgersClient
from .types.get_financial_report_request_group_by import GetFinancialReportRequestGroupBy
from .types.get_financial_report_request_report_type import GetFinancialReportRequestReportType
from .types.get_financial_report_response import GetFinancialReportResponse


class LedgersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLedgersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLedgersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLedgersClient
        """
        return self._raw_client

    def get_financial_report(
        self,
        *,
        account_id: str,
        report_type: GetFinancialReportRequestReportType,
        currency: typing.Optional[str] = None,
        in_currency: typing.Optional[str] = None,
        from_date: typing.Optional[str] = None,
        to_date: typing.Optional[str] = None,
        group_by: typing.Optional[GetFinancialReportRequestGroupBy] = None,
        timezone: typing.Optional[str] = None,
        cumulative: typing.Optional[bool] = None,
        scope_account_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFinancialReportResponse:
        """
        Returns a financial report — balance activity, income statement, or balance summary — for an account over a date range.

        Parameters
        ----------
        account_id : str
            The owning account ID (a biz_ identifier), or `global` for a platform-wide report across all ledger accounts (requires internal admin access).

        report_type : GetFinancialReportRequestReportType
            The type of financial report to generate.

        currency : typing.Optional[str]
            Filter rows to this currency, for example `usd`. Defaults to `usd` unless `in_currency` is provided.

        in_currency : typing.Optional[str]
            Aggregate all activity into this display currency via FX conversion.

        from_date : typing.Optional[str]
            Start of the report window as an ISO 8601 timestamp (UTC). Required for platform-wide (global) reports.

        to_date : typing.Optional[str]
            End of the report window as an ISO 8601 timestamp (UTC). Required for platform-wide (global) reports.

        group_by : typing.Optional[GetFinancialReportRequestGroupBy]
            Grouping granularity for report rows.

        timezone : typing.Optional[str]
            IANA timezone (for example `America/New_York`) used to bucket report periods and to interpret calendar-day boundaries for balance snapshots. Defaults to UTC. from_date/to_date remain exact instants regardless of this setting.

        cumulative : typing.Optional[bool]
            Platform-wide (global) reports only: when true, return cumulative balances as of to_date (all history, no lower bound) instead of activity within the period.

        scope_account_id : typing.Optional[str]
            Platform-wide (global) reports only: narrow the report to ledger lines on the ledger account owned by this account ID (a biz_ identifier). Ignored unless account_id is `global`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFinancialReportResponse
            financial report returned

        Examples
        --------
        from whop_sdk import Whop

        client = Whop(
            "2026-08-21-1",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )
        client.ledgers.get_financial_report(
            account_id="account_id",
            report_type="balance_summary",
        )
        """
        _response = self._raw_client.get_financial_report(
            account_id=account_id,
            report_type=report_type,
            currency=currency,
            in_currency=in_currency,
            from_date=from_date,
            to_date=to_date,
            group_by=group_by,
            timezone=timezone,
            cumulative=cumulative,
            scope_account_id=scope_account_id,
            request_options=request_options,
        )
        return _response.data


class AsyncLedgersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLedgersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLedgersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLedgersClient
        """
        return self._raw_client

    async def get_financial_report(
        self,
        *,
        account_id: str,
        report_type: GetFinancialReportRequestReportType,
        currency: typing.Optional[str] = None,
        in_currency: typing.Optional[str] = None,
        from_date: typing.Optional[str] = None,
        to_date: typing.Optional[str] = None,
        group_by: typing.Optional[GetFinancialReportRequestGroupBy] = None,
        timezone: typing.Optional[str] = None,
        cumulative: typing.Optional[bool] = None,
        scope_account_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFinancialReportResponse:
        """
        Returns a financial report — balance activity, income statement, or balance summary — for an account over a date range.

        Parameters
        ----------
        account_id : str
            The owning account ID (a biz_ identifier), or `global` for a platform-wide report across all ledger accounts (requires internal admin access).

        report_type : GetFinancialReportRequestReportType
            The type of financial report to generate.

        currency : typing.Optional[str]
            Filter rows to this currency, for example `usd`. Defaults to `usd` unless `in_currency` is provided.

        in_currency : typing.Optional[str]
            Aggregate all activity into this display currency via FX conversion.

        from_date : typing.Optional[str]
            Start of the report window as an ISO 8601 timestamp (UTC). Required for platform-wide (global) reports.

        to_date : typing.Optional[str]
            End of the report window as an ISO 8601 timestamp (UTC). Required for platform-wide (global) reports.

        group_by : typing.Optional[GetFinancialReportRequestGroupBy]
            Grouping granularity for report rows.

        timezone : typing.Optional[str]
            IANA timezone (for example `America/New_York`) used to bucket report periods and to interpret calendar-day boundaries for balance snapshots. Defaults to UTC. from_date/to_date remain exact instants regardless of this setting.

        cumulative : typing.Optional[bool]
            Platform-wide (global) reports only: when true, return cumulative balances as of to_date (all history, no lower bound) instead of activity within the period.

        scope_account_id : typing.Optional[str]
            Platform-wide (global) reports only: narrow the report to ledger lines on the ledger account owned by this account ID (a biz_ identifier). Ignored unless account_id is `global`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFinancialReportResponse
            financial report returned

        Examples
        --------
        import asyncio

        from whop_sdk import AsyncWhop

        client = AsyncWhop(
            "2026-08-21-1",
            idempotency_key="YOUR_IDEMPOTENCY_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ledgers.get_financial_report(
                account_id="account_id",
                report_type="balance_summary",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_financial_report(
            account_id=account_id,
            report_type=report_type,
            currency=currency,
            in_currency=in_currency,
            from_date=from_date,
            to_date=to_date,
            group_by=group_by,
            timezone=timezone,
            cumulative=cumulative,
            scope_account_id=scope_account_id,
            request_options=request_options,
        )
        return _response.data
