# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_card_canceled_payload_data_limit_frequency import PostCardCanceledPayloadDataLimitFrequency


class PostCardCanceledPayloadDataLimit(UniversalBaseModel):
    """
    The spending limit configuration.
    """

    amount: float = pydantic.Field()
    """
    The limit amount in dollars.
    """

    frequency: PostCardCanceledPayloadDataLimitFrequency = pydantic.Field()
    """
    The window the limit amount applies to. `per_transaction` caps each individual authorization and is what a limit set with `transaction_limit` reports.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
