# This file was auto-generated by Fern from our API Definition.

import typing

PostResolutionCenterCaseCreatedPayloadType = typing.Union[typing.Literal["resolution_center_case.created"], typing.Any]
