# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .summary_resolution_center_cases_response_groups import SummaryResolutionCenterCasesResponseGroups


class SummaryResolutionCenterCasesResponse(UniversalBaseModel):
    groups: SummaryResolutionCenterCasesResponseGroups = pydantic.Field()
    """
    One entry per requested breakdown, keyed by the field it groups on. A field you did not ask for is absent.
    """

    total: int = pydantic.Field()
    """
    How many cases match the filters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
