# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_people_response_data_item_last_source_ad import ListPeopleResponseDataItemLastSourceAd
from .list_people_response_data_item_last_source_ad_group import ListPeopleResponseDataItemLastSourceAdGroup
from .list_people_response_data_item_last_source_campaign import ListPeopleResponseDataItemLastSourceCampaign
from .list_people_response_data_item_last_source_type import ListPeopleResponseDataItemLastSourceType


class ListPeopleResponseDataItemLastSource(UniversalBaseModel):
    """
    Where a visit came from: a whop ad click, a lead form, an external ad, or a referring site.
    """

    ad: typing.Optional[ListPeopleResponseDataItemLastSourceAd] = None
    ad_group: typing.Optional[ListPeopleResponseDataItemLastSourceAdGroup] = None
    campaign: typing.Optional[ListPeopleResponseDataItemLastSourceCampaign] = None
    domain: typing.Optional[str] = None
    occurred_at: typing.Optional[dt.datetime] = None
    platform: typing.Optional[str] = None
    type: ListPeopleResponseDataItemLastSourceType
    utm_source: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
