# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieve_breakdown_response_activity_filters_direction import RetrieveBreakdownResponseActivityFiltersDirection


class RetrieveBreakdownResponseActivityFilters(UniversalBaseModel):
    direction: RetrieveBreakdownResponseActivityFiltersDirection
    line_types: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
