# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.product_affiliate import ProductAffiliate
from .types.list_product_affiliates_request_status import ListProductAffiliatesRequestStatus
from .types.list_product_affiliates_response import ListProductAffiliatesResponse
from pydantic import ValidationError


class RawProductAffiliatesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        account_id: str,
        query: typing.Optional[str] = None,
        status: typing.Optional[ListProductAffiliatesRequestStatus] = None,
        product_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ProductAffiliate, ListProductAffiliatesResponse]:
        """
        Lists affiliate enrollments for an account's products, newest first, including affiliates who have not made a referral. Requires `affiliate:basic:read` on the account. Email addresses and email search also require `member:email:read`.

        Parameters
        ----------
        account_id : str
            Account whose product affiliates are listed (`biz_` tag).

        query : typing.Optional[str]
            Matches the start of the affiliate's username or of any word in their name, or their exact email (with `member:email:read`).

        status : typing.Optional[ListProductAffiliatesRequestStatus]
            Only product affiliates with this status.

        product_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only product affiliates of these products.

        created_after : typing.Optional[dt.datetime]
            Only signups at or after this ISO 8601 timestamp.

        created_before : typing.Optional[dt.datetime]
            Only signups before this ISO 8601 timestamp.

        first : typing.Optional[int]
            Number of results to return from the start of the range.

        after : typing.Optional[str]
            Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page.

        last : typing.Optional[int]
            Number of results to return from the end of the range.

        before : typing.Optional[str]
            Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ProductAffiliate, ListProductAffiliatesResponse]
            product affiliates listed
        """
        _response = self._client_wrapper.httpx_client.request(
            "product_affiliates",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            params={
                "account_id": account_id,
                "query": query,
                "status": status,
                "product_ids": product_ids,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListProductAffiliatesResponse,
                    parse_obj_as(
                        type_=ListProductAffiliatesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        account_id=account_id,
                        query=query,
                        status=status,
                        product_ids=product_ids,
                        created_after=created_after,
                        created_before=created_before,
                        first=first,
                        after=_parsed_next,
                        last=last,
                        before=before,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawProductAffiliatesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        account_id: str,
        query: typing.Optional[str] = None,
        status: typing.Optional[ListProductAffiliatesRequestStatus] = None,
        product_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ProductAffiliate, ListProductAffiliatesResponse]:
        """
        Lists affiliate enrollments for an account's products, newest first, including affiliates who have not made a referral. Requires `affiliate:basic:read` on the account. Email addresses and email search also require `member:email:read`.

        Parameters
        ----------
        account_id : str
            Account whose product affiliates are listed (`biz_` tag).

        query : typing.Optional[str]
            Matches the start of the affiliate's username or of any word in their name, or their exact email (with `member:email:read`).

        status : typing.Optional[ListProductAffiliatesRequestStatus]
            Only product affiliates with this status.

        product_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Only product affiliates of these products.

        created_after : typing.Optional[dt.datetime]
            Only signups at or after this ISO 8601 timestamp.

        created_before : typing.Optional[dt.datetime]
            Only signups before this ISO 8601 timestamp.

        first : typing.Optional[int]
            Number of results to return from the start of the range.

        after : typing.Optional[str]
            Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page.

        last : typing.Optional[int]
            Number of results to return from the end of the range.

        before : typing.Optional[str]
            Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ProductAffiliate, ListProductAffiliatesResponse]
            product affiliates listed
        """
        _response = await self._client_wrapper.httpx_client.request(
            "product_affiliates",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            params={
                "account_id": account_id,
                "query": query,
                "status": status,
                "product_ids": product_ids,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListProductAffiliatesResponse,
                    parse_obj_as(
                        type_=ListProductAffiliatesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            account_id=account_id,
                            query=query,
                            status=status,
                            product_ids=product_ids,
                            created_after=created_after,
                            created_before=created_before,
                            first=first,
                            after=_parsed_next,
                            last=last,
                            before=before,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
