# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...errors.bad_request_error import BadRequestError
from ...errors.unauthorized_error import UnauthorizedError
from .types.list_reports_response import ListReportsResponse
from .types.platform_trends_reports_request_breakdown_by import PlatformTrendsReportsRequestBreakdownBy
from .types.platform_trends_reports_request_direction import PlatformTrendsReportsRequestDirection
from .types.platform_trends_reports_request_order import PlatformTrendsReportsRequestOrder
from .types.platform_trends_reports_response import PlatformTrendsReportsResponse
from pydantic import ValidationError


class RawReportsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ListReportsResponse]:
        """
        Lists every report: the aggregates that are not bucketed over time. Each entry names the report's path, its window kind, the breakdowns it accepts and its columns. A property column is an attribute of the row and lists the breakdowns it can ride along with. A metric column is a number measured over the row, with the unit that sets its JSON type, the aggregate that says how to combine it across rows, and the breakdowns and windows it supports. For a bucketed series, use `GET /stats/time_series`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListReportsResponse]
            Every report you can retrieve.
        """
        _response = self._client_wrapper.httpx_client.request(
            "stats/reports",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListReportsResponse,
                    parse_obj_as(
                        type_=ListReportsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def platform_trends(
        self,
        *,
        breakdown_by: typing.Optional[PlatformTrendsReportsRequestBreakdownBy] = None,
        columns: typing.Optional[str] = None,
        windows: typing.Optional[str] = None,
        time_zone: typing.Optional[str] = None,
        order: typing.Optional[PlatformTrendsReportsRequestOrder] = None,
        direction: typing.Optional[PlatformTrendsReportsRequestDirection] = None,
        convert_to: typing.Optional[str] = None,
        business_type: typing.Optional[str] = None,
        industry_type: typing.Optional[str] = None,
        account_country: typing.Optional[str] = None,
        customer_country: typing.Optional[str] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PlatformTrendsReportsResponse]:
        """
        Payments across all of Whop, for up to four windows at once. Break rows down by business type, industry type, account country or customer country, and let the business type ride along on industry type rows. The report covers the whole platform, so it takes no `account_id` and any authenticated caller can read it. A breakdown value with fewer than three businesses behind it is left out, and a filtered total that small comes back with every metric `null`.

        Parameters
        ----------
        breakdown_by : typing.Optional[PlatformTrendsReportsRequestBreakdownBy]
            What each row is. Omit it for one row per window, holding the window's total.

        columns : typing.Optional[str]
            Comma-separated properties and metrics to return on each row. Defaults to `gross_revenue,businesses`.

        windows : typing.Optional[str]
            Comma-separated windows, at most four: `1d`, `7d`, `30d`, `90d`, `365d`, `mtd`, `qtd`, `ytd`, `all_time`, an explicit `2026-09-01..2026-10-01`, any of these prefixed `prev:` for the equal-length period before, or suffixed `@2026-09-01` to end earlier. Defaults to `30d`.

        time_zone : typing.Optional[str]
            IANA zone that day, month, quarter and year boundaries fall in. Defaults to `Etc/UTC`.

        order : typing.Optional[PlatformTrendsReportsRequestOrder]
            The requested metric that ranks rows, by its value in the first window. Defaults to the first requested metric.

        direction : typing.Optional[PlatformTrendsReportsRequestDirection]
            Ranking direction. Defaults to `desc`.

        convert_to : typing.Optional[str]
            Currency every money metric is converted into. Defaults to `usd`.

        business_type : typing.Optional[str]
            Only counts payments to businesses of these comma-separated business types, such as `education`.

        industry_type : typing.Optional[str]
            Only counts payments to businesses in these comma-separated industry types, such as `options_trading`.

        account_country : typing.Optional[str]
            Only counts payments to accounts located in these comma-separated countries, as ISO 3166-1 alpha-2 codes such as `US`.

        customer_country : typing.Optional[str]
            Only counts payments from customers in these comma-separated countries, as ISO 3166-1 alpha-2 codes such as `US`.

        first : typing.Optional[int]
            Number of results to return from the start of the range.

        after : typing.Optional[str]
            Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PlatformTrendsReportsResponse]
            Platform trends for each requested window, with rows in the same order in every window.
        """
        _response = self._client_wrapper.httpx_client.request(
            "stats/reports/platform_trends",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            params={
                "breakdown_by": breakdown_by,
                "columns": columns,
                "windows": windows,
                "time_zone": time_zone,
                "order": order,
                "direction": direction,
                "convert_to": convert_to,
                "business_type": business_type,
                "industry_type": industry_type,
                "account_country": account_country,
                "customer_country": customer_country,
                "first": first,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlatformTrendsReportsResponse,
                    parse_obj_as(
                        type_=PlatformTrendsReportsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawReportsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListReportsResponse]:
        """
        Lists every report: the aggregates that are not bucketed over time. Each entry names the report's path, its window kind, the breakdowns it accepts and its columns. A property column is an attribute of the row and lists the breakdowns it can ride along with. A metric column is a number measured over the row, with the unit that sets its JSON type, the aggregate that says how to combine it across rows, and the breakdowns and windows it supports. For a bucketed series, use `GET /stats/time_series`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListReportsResponse]
            Every report you can retrieve.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "stats/reports",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListReportsResponse,
                    parse_obj_as(
                        type_=ListReportsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def platform_trends(
        self,
        *,
        breakdown_by: typing.Optional[PlatformTrendsReportsRequestBreakdownBy] = None,
        columns: typing.Optional[str] = None,
        windows: typing.Optional[str] = None,
        time_zone: typing.Optional[str] = None,
        order: typing.Optional[PlatformTrendsReportsRequestOrder] = None,
        direction: typing.Optional[PlatformTrendsReportsRequestDirection] = None,
        convert_to: typing.Optional[str] = None,
        business_type: typing.Optional[str] = None,
        industry_type: typing.Optional[str] = None,
        account_country: typing.Optional[str] = None,
        customer_country: typing.Optional[str] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PlatformTrendsReportsResponse]:
        """
        Payments across all of Whop, for up to four windows at once. Break rows down by business type, industry type, account country or customer country, and let the business type ride along on industry type rows. The report covers the whole platform, so it takes no `account_id` and any authenticated caller can read it. A breakdown value with fewer than three businesses behind it is left out, and a filtered total that small comes back with every metric `null`.

        Parameters
        ----------
        breakdown_by : typing.Optional[PlatformTrendsReportsRequestBreakdownBy]
            What each row is. Omit it for one row per window, holding the window's total.

        columns : typing.Optional[str]
            Comma-separated properties and metrics to return on each row. Defaults to `gross_revenue,businesses`.

        windows : typing.Optional[str]
            Comma-separated windows, at most four: `1d`, `7d`, `30d`, `90d`, `365d`, `mtd`, `qtd`, `ytd`, `all_time`, an explicit `2026-09-01..2026-10-01`, any of these prefixed `prev:` for the equal-length period before, or suffixed `@2026-09-01` to end earlier. Defaults to `30d`.

        time_zone : typing.Optional[str]
            IANA zone that day, month, quarter and year boundaries fall in. Defaults to `Etc/UTC`.

        order : typing.Optional[PlatformTrendsReportsRequestOrder]
            The requested metric that ranks rows, by its value in the first window. Defaults to the first requested metric.

        direction : typing.Optional[PlatformTrendsReportsRequestDirection]
            Ranking direction. Defaults to `desc`.

        convert_to : typing.Optional[str]
            Currency every money metric is converted into. Defaults to `usd`.

        business_type : typing.Optional[str]
            Only counts payments to businesses of these comma-separated business types, such as `education`.

        industry_type : typing.Optional[str]
            Only counts payments to businesses in these comma-separated industry types, such as `options_trading`.

        account_country : typing.Optional[str]
            Only counts payments to accounts located in these comma-separated countries, as ISO 3166-1 alpha-2 codes such as `US`.

        customer_country : typing.Optional[str]
            Only counts payments from customers in these comma-separated countries, as ISO 3166-1 alpha-2 codes such as `US`.

        first : typing.Optional[int]
            Number of results to return from the start of the range.

        after : typing.Optional[str]
            Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PlatformTrendsReportsResponse]
            Platform trends for each requested window, with rows in the same order in every window.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "stats/reports/platform_trends",
            base_url=self._client_wrapper.get_environment().api,
            method="GET",
            params={
                "breakdown_by": breakdown_by,
                "columns": columns,
                "windows": windows,
                "time_zone": time_zone,
                "order": order,
                "direction": direction,
                "convert_to": convert_to,
                "business_type": business_type,
                "industry_type": industry_type,
                "account_country": account_country,
                "customer_country": customer_country,
                "first": first,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PlatformTrendsReportsResponse,
                    parse_obj_as(
                        type_=PlatformTrendsReportsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
