# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreatePaymentsRequestLineItemsItem(UniversalBaseModel):
    plan_id: str = pydantic.Field()
    """
    An existing plan to charge for, prefixed `plan_`. Each plan may appear once — use `quantity` for multiple units.
    """

    quantity: typing.Optional[int] = pydantic.Field(default=None)
    """
    How many units of the plan to purchase. Defaults to 1; more than 1 requires the plan to allow multiple quantities.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
