# This file was auto-generated by Fern from our API Definition.

import typing

ListPaymentsRequestStatus = typing.Union[
    typing.Literal["open", "authorized", "paid", "pending", "uncollectible", "unresolved", "void"], typing.Any
]
