# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .list_reports_response import ListReportsResponse
    from .list_reports_response_data_item import ListReportsResponseDataItem
    from .list_reports_response_data_item_columns_item import ListReportsResponseDataItemColumnsItem
    from .list_reports_response_data_item_columns_item_aggregate import ListReportsResponseDataItemColumnsItemAggregate
    from .list_reports_response_data_item_columns_item_set import ListReportsResponseDataItemColumnsItemSet
    from .list_reports_response_data_item_columns_item_type import ListReportsResponseDataItemColumnsItemType
    from .list_reports_response_data_item_columns_item_unit import ListReportsResponseDataItemColumnsItemUnit
    from .list_reports_response_data_item_window_kind import ListReportsResponseDataItemWindowKind
_dynamic_imports: typing.Dict[str, str] = {
    "ListReportsResponse": ".list_reports_response",
    "ListReportsResponseDataItem": ".list_reports_response_data_item",
    "ListReportsResponseDataItemColumnsItem": ".list_reports_response_data_item_columns_item",
    "ListReportsResponseDataItemColumnsItemAggregate": ".list_reports_response_data_item_columns_item_aggregate",
    "ListReportsResponseDataItemColumnsItemSet": ".list_reports_response_data_item_columns_item_set",
    "ListReportsResponseDataItemColumnsItemType": ".list_reports_response_data_item_columns_item_type",
    "ListReportsResponseDataItemColumnsItemUnit": ".list_reports_response_data_item_columns_item_unit",
    "ListReportsResponseDataItemWindowKind": ".list_reports_response_data_item_window_kind",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListReportsResponse",
    "ListReportsResponseDataItem",
    "ListReportsResponseDataItemColumnsItem",
    "ListReportsResponseDataItemColumnsItemAggregate",
    "ListReportsResponseDataItemColumnsItemSet",
    "ListReportsResponseDataItemColumnsItemType",
    "ListReportsResponseDataItemColumnsItemUnit",
    "ListReportsResponseDataItemWindowKind",
]
