# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.forbidden_error import ForbiddenError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from .types.list_api_logs_request_http_method import ListApiLogsRequestHttpMethod
from .types.list_api_logs_request_status import ListApiLogsRequestStatus
from .types.list_api_logs_response import ListApiLogsResponse
from .types.list_api_logs_response_data_item import ListApiLogsResponseDataItem
from pydantic import ValidationError


class RawApiLogsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        account_id: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        operation_name: typing.Optional[str] = None,
        http_method: typing.Optional[ListApiLogsRequestHttpMethod] = None,
        status: typing.Optional[ListApiLogsRequestStatus] = None,
        api_key_id: typing.Optional[str] = None,
        min_duration_ms: typing.Optional[int] = None,
        max_duration_ms: typing.Optional[int] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListApiLogsResponseDataItem, ListApiLogsResponse]:
        """
        Lists the requests served by Whop's API with the account's API keys, newest first — every surface (GraphQL, REST, and native /api/v1), reads and failed requests included.

        Parameters
        ----------
        account_id : typing.Optional[str]
            The account (biz_*) whose API logs to list. Defaults to the authenticated account.

        created_after : typing.Optional[str]
            Only return requests served at or after this ISO 8601 timestamp. Defaults to 7 days before created_before, or 7 days ago.

        created_before : typing.Optional[str]
            Only return requests served before this ISO 8601 timestamp.

        operation_name : typing.Optional[str]
            Only return requests for this operation, matched exactly against the operation_name shown on each log row (for example api/v1/products#create).

        http_method : typing.Optional[ListApiLogsRequestHttpMethod]
            Only return requests made with this HTTP method.

        status : typing.Optional[ListApiLogsRequestStatus]
            Only return requests that finished with this status.

        api_key_id : typing.Optional[str]
            Only return requests made with this API key (apik_…).

        min_duration_ms : typing.Optional[int]
            Only return requests that took at least this many milliseconds.

        max_duration_ms : typing.Optional[int]
            Only return requests that took at most this many milliseconds.

        first : typing.Optional[int]
            Number of logs to return.

        after : typing.Optional[str]
            Cursor to fetch the page after (from page_info.end_cursor).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListApiLogsResponseDataItem, ListApiLogsResponse]
            api logs listed
        """
        _response = self._client_wrapper.httpx_client.request(
            "api_logs",
            method="GET",
            params={
                "account_id": account_id,
                "created_after": created_after,
                "created_before": created_before,
                "operation_name": operation_name,
                "http_method": http_method,
                "status": status,
                "api_key_id": api_key_id,
                "min_duration_ms": min_duration_ms,
                "max_duration_ms": max_duration_ms,
                "first": first,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListApiLogsResponse,
                    parse_obj_as(
                        type_=ListApiLogsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        account_id=account_id,
                        created_after=created_after,
                        created_before=created_before,
                        operation_name=operation_name,
                        http_method=http_method,
                        status=status,
                        api_key_id=api_key_id,
                        min_duration_ms=min_duration_ms,
                        max_duration_ms=max_duration_ms,
                        first=first,
                        after=_parsed_next,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawApiLogsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        account_id: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        operation_name: typing.Optional[str] = None,
        http_method: typing.Optional[ListApiLogsRequestHttpMethod] = None,
        status: typing.Optional[ListApiLogsRequestStatus] = None,
        api_key_id: typing.Optional[str] = None,
        min_duration_ms: typing.Optional[int] = None,
        max_duration_ms: typing.Optional[int] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListApiLogsResponseDataItem, ListApiLogsResponse]:
        """
        Lists the requests served by Whop's API with the account's API keys, newest first — every surface (GraphQL, REST, and native /api/v1), reads and failed requests included.

        Parameters
        ----------
        account_id : typing.Optional[str]
            The account (biz_*) whose API logs to list. Defaults to the authenticated account.

        created_after : typing.Optional[str]
            Only return requests served at or after this ISO 8601 timestamp. Defaults to 7 days before created_before, or 7 days ago.

        created_before : typing.Optional[str]
            Only return requests served before this ISO 8601 timestamp.

        operation_name : typing.Optional[str]
            Only return requests for this operation, matched exactly against the operation_name shown on each log row (for example api/v1/products#create).

        http_method : typing.Optional[ListApiLogsRequestHttpMethod]
            Only return requests made with this HTTP method.

        status : typing.Optional[ListApiLogsRequestStatus]
            Only return requests that finished with this status.

        api_key_id : typing.Optional[str]
            Only return requests made with this API key (apik_…).

        min_duration_ms : typing.Optional[int]
            Only return requests that took at least this many milliseconds.

        max_duration_ms : typing.Optional[int]
            Only return requests that took at most this many milliseconds.

        first : typing.Optional[int]
            Number of logs to return.

        after : typing.Optional[str]
            Cursor to fetch the page after (from page_info.end_cursor).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListApiLogsResponseDataItem, ListApiLogsResponse]
            api logs listed
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api_logs",
            method="GET",
            params={
                "account_id": account_id,
                "created_after": created_after,
                "created_before": created_before,
                "operation_name": operation_name,
                "http_method": http_method,
                "status": status,
                "api_key_id": api_key_id,
                "min_duration_ms": min_duration_ms,
                "max_duration_ms": max_duration_ms,
                "first": first,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListApiLogsResponse,
                    parse_obj_as(
                        type_=ListApiLogsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            account_id=account_id,
                            created_after=created_after,
                            created_before=created_before,
                            operation_name=operation_name,
                            http_method=http_method,
                            status=status,
                            api_key_id=api_key_id,
                            min_duration_ms=min_duration_ms,
                            max_duration_ms=max_duration_ms,
                            first=first,
                            after=_parsed_next,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
