# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_events_request_action_source import CreateEventsRequestActionSource
    from .create_events_request_context import CreateEventsRequestContext
    from .create_events_request_currency import CreateEventsRequestCurrency
    from .create_events_request_user import CreateEventsRequestUser
    from .create_events_request_user_gender import CreateEventsRequestUserGender
    from .create_events_response import CreateEventsResponse
    from .list_events_request_attribution_model import ListEventsRequestAttributionModel
    from .list_events_request_direction import ListEventsRequestDirection
    from .list_events_response import ListEventsResponse
    from .list_events_response_data_item import ListEventsResponseDataItem
    from .list_events_response_data_item_context import ListEventsResponseDataItemContext
    from .list_events_response_data_item_context_source_type import ListEventsResponseDataItemContextSourceType
    from .list_events_response_data_item_questions_item import ListEventsResponseDataItemQuestionsItem
    from .list_events_response_data_item_related import ListEventsResponseDataItemRelated
    from .list_events_response_data_item_related_account import ListEventsResponseDataItemRelatedAccount
    from .list_events_response_data_item_related_ad import ListEventsResponseDataItemRelatedAd
    from .list_events_response_data_item_related_ad_campaign import ListEventsResponseDataItemRelatedAdCampaign
    from .list_events_response_data_item_related_ad_group import ListEventsResponseDataItemRelatedAdGroup
    from .list_events_response_data_item_related_app import ListEventsResponseDataItemRelatedApp
    from .list_events_response_data_item_related_audience import ListEventsResponseDataItemRelatedAudience
    from .list_events_response_data_item_related_audience_audience_type import (
        ListEventsResponseDataItemRelatedAudienceAudienceType,
    )
    from .list_events_response_data_item_related_audience_source_type import (
        ListEventsResponseDataItemRelatedAudienceSourceType,
    )
    from .list_events_response_data_item_related_payment import ListEventsResponseDataItemRelatedPayment
    from .list_events_response_data_item_related_plan import ListEventsResponseDataItemRelatedPlan
    from .list_events_response_data_item_related_product import ListEventsResponseDataItemRelatedProduct
    from .list_events_response_data_item_related_user import ListEventsResponseDataItemRelatedUser
    from .list_events_response_data_item_user import ListEventsResponseDataItemUser
    from .list_events_response_page_info import ListEventsResponsePageInfo
    from .pulse_events_response import PulseEventsResponse
    from .pulse_events_response_data_item import PulseEventsResponseDataItem
    from .pulse_events_response_data_item_event_name import PulseEventsResponseDataItemEventName
    from .pulse_events_response_data_item_type import PulseEventsResponseDataItemType
    from .pulse_events_response_data_item_user import PulseEventsResponseDataItemUser
    from .pulse_events_response_page_info import PulseEventsResponsePageInfo
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEventsRequestActionSource": ".create_events_request_action_source",
    "CreateEventsRequestContext": ".create_events_request_context",
    "CreateEventsRequestCurrency": ".create_events_request_currency",
    "CreateEventsRequestUser": ".create_events_request_user",
    "CreateEventsRequestUserGender": ".create_events_request_user_gender",
    "CreateEventsResponse": ".create_events_response",
    "ListEventsRequestAttributionModel": ".list_events_request_attribution_model",
    "ListEventsRequestDirection": ".list_events_request_direction",
    "ListEventsResponse": ".list_events_response",
    "ListEventsResponseDataItem": ".list_events_response_data_item",
    "ListEventsResponseDataItemContext": ".list_events_response_data_item_context",
    "ListEventsResponseDataItemContextSourceType": ".list_events_response_data_item_context_source_type",
    "ListEventsResponseDataItemQuestionsItem": ".list_events_response_data_item_questions_item",
    "ListEventsResponseDataItemRelated": ".list_events_response_data_item_related",
    "ListEventsResponseDataItemRelatedAccount": ".list_events_response_data_item_related_account",
    "ListEventsResponseDataItemRelatedAd": ".list_events_response_data_item_related_ad",
    "ListEventsResponseDataItemRelatedAdCampaign": ".list_events_response_data_item_related_ad_campaign",
    "ListEventsResponseDataItemRelatedAdGroup": ".list_events_response_data_item_related_ad_group",
    "ListEventsResponseDataItemRelatedApp": ".list_events_response_data_item_related_app",
    "ListEventsResponseDataItemRelatedAudience": ".list_events_response_data_item_related_audience",
    "ListEventsResponseDataItemRelatedAudienceAudienceType": ".list_events_response_data_item_related_audience_audience_type",
    "ListEventsResponseDataItemRelatedAudienceSourceType": ".list_events_response_data_item_related_audience_source_type",
    "ListEventsResponseDataItemRelatedPayment": ".list_events_response_data_item_related_payment",
    "ListEventsResponseDataItemRelatedPlan": ".list_events_response_data_item_related_plan",
    "ListEventsResponseDataItemRelatedProduct": ".list_events_response_data_item_related_product",
    "ListEventsResponseDataItemRelatedUser": ".list_events_response_data_item_related_user",
    "ListEventsResponseDataItemUser": ".list_events_response_data_item_user",
    "ListEventsResponsePageInfo": ".list_events_response_page_info",
    "PulseEventsResponse": ".pulse_events_response",
    "PulseEventsResponseDataItem": ".pulse_events_response_data_item",
    "PulseEventsResponseDataItemEventName": ".pulse_events_response_data_item_event_name",
    "PulseEventsResponseDataItemType": ".pulse_events_response_data_item_type",
    "PulseEventsResponseDataItemUser": ".pulse_events_response_data_item_user",
    "PulseEventsResponsePageInfo": ".pulse_events_response_page_info",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEventsRequestActionSource",
    "CreateEventsRequestContext",
    "CreateEventsRequestCurrency",
    "CreateEventsRequestUser",
    "CreateEventsRequestUserGender",
    "CreateEventsResponse",
    "ListEventsRequestAttributionModel",
    "ListEventsRequestDirection",
    "ListEventsResponse",
    "ListEventsResponseDataItem",
    "ListEventsResponseDataItemContext",
    "ListEventsResponseDataItemContextSourceType",
    "ListEventsResponseDataItemQuestionsItem",
    "ListEventsResponseDataItemRelated",
    "ListEventsResponseDataItemRelatedAccount",
    "ListEventsResponseDataItemRelatedAd",
    "ListEventsResponseDataItemRelatedAdCampaign",
    "ListEventsResponseDataItemRelatedAdGroup",
    "ListEventsResponseDataItemRelatedApp",
    "ListEventsResponseDataItemRelatedAudience",
    "ListEventsResponseDataItemRelatedAudienceAudienceType",
    "ListEventsResponseDataItemRelatedAudienceSourceType",
    "ListEventsResponseDataItemRelatedPayment",
    "ListEventsResponseDataItemRelatedPlan",
    "ListEventsResponseDataItemRelatedProduct",
    "ListEventsResponseDataItemRelatedUser",
    "ListEventsResponseDataItemUser",
    "ListEventsResponsePageInfo",
    "PulseEventsResponse",
    "PulseEventsResponseDataItem",
    "PulseEventsResponseDataItemEventName",
    "PulseEventsResponseDataItemType",
    "PulseEventsResponseDataItemUser",
    "PulseEventsResponsePageInfo",
]
