# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_events_request_user_gender import CreateEventsRequestUserGender


class CreateEventsRequestUser(UniversalBaseModel):
    """
    User identity and profile data.
    """

    anonymous_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An anonymous identifier for the user.
    """

    birthdate: typing.Optional[str] = pydantic.Field(default=None)
    """
    Date of birth (YYYY-MM-DD).
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Country.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address.
    """

    external_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An external identifier for the user.
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    First name.
    """

    gender: typing.Optional[CreateEventsRequestUserGender] = pydantic.Field(default=None)
    """
    Gender.
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last name.
    """

    linked_anonymous_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A second anonymous identifier to link to this user (e.g. captured across an iframe boundary).
    """

    linked_wuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    A wuid from a linked frame, captured across an iframe boundary.
    """

    member_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Whop member ID.
    """

    membership_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Whop membership ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full display name.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number.
    """

    postal_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Postal code.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or region.
    """

    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Whop user ID.
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Username.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
