# This file was auto-generated by Fern from our API Definition.

import typing

CreateEventsRequestActionSource = typing.Union[
    typing.Literal[
        "email",
        "website",
        "app",
        "phone_call",
        "chat",
        "physical_store",
        "system_generated",
        "business_messaging",
        "other",
    ],
    typing.Any,
]
