# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.ledger_activity import LedgerActivity
from .post_financial_activity_funds_available_payload_api_version import (
    PostFinancialActivityFundsAvailablePayloadApiVersion,
)
from .post_financial_activity_funds_available_payload_type import PostFinancialActivityFundsAvailablePayloadType


class PostFinancialActivityFundsAvailablePayload(UniversalBaseModel):
    account_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The account ID that this webhook event is associated with
    """

    api_version: PostFinancialActivityFundsAvailablePayloadApiVersion = pydantic.Field()
    """
    The API version for this webhook
    """

    api_version_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    The dated API version (Api-Version-Date) the payload is serialized to
    """

    data: LedgerActivity
    id: str = pydantic.Field()
    """
    A unique ID for every single webhook request
    """

    previous_attributes: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    For some `.updated` events, the old values of the payload fields that changed, keyed by field name. Omitted when no capture is available for the event
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    The timestamp in ISO 8601 format that the webhook was sent at on the server
    """

    type: PostFinancialActivityFundsAvailablePayloadType = pydantic.Field()
    """
    The webhook event type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
