# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.payment_method_types import PaymentMethodTypes


class CreateInvoicesRequestProductPlanPaymentMethodConfiguration(UniversalBaseModel):
    """
    The explicit payment method configuration for the plan. If not provided, the platform or company's defaults will apply.
    """

    disabled: typing.List[PaymentMethodTypes] = pydantic.Field()
    """
    An array of payment method identifiers that are explicitly disabled. Only applies if the include_platform_defaults is true.
    """

    enabled: typing.List[PaymentMethodTypes] = pydantic.Field()
    """
    An array of payment method identifiers that are explicitly enabled. This means these payment methods will be shown on checkout. Example use case is to only enable a specific payment method like cashapp, or extending the platform defaults with additional methods.
    """

    include_platform_defaults: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether Whop's platform default payment method enablement settings are included in this configuration. The full list of default payment methods can be found in the documentation at docs.whop.com/payments.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
