# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.invoice_list_item import InvoiceListItem
from ...types.page_info import PageInfo


class ListInvoicesResponse(UniversalBaseModel):
    """
    The connection type for PublicInvoice.
    """

    data: typing.List[InvoiceListItem] = pydantic.Field()
    """
    A list of nodes.
    """

    page_info: PageInfo = pydantic.Field()
    """
    Information to aid in pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
