# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_chat_reaction_created_payload_data_channel_type import PostChatReactionCreatedPayloadDataChannelType


class PostChatReactionCreatedPayloadDataChannel(UniversalBaseModel):
    experience_id: typing.Optional[str] = None
    id: str
    type: PostChatReactionCreatedPayloadDataChannelType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
