# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AccessToken(UniversalBaseModel):
    """
    A short-lived access token used to authenticate API requests on behalf of a user.
    """

    expires_at: dt.datetime = pydantic.Field()
    """
    The timestamp after which this access token is no longer valid and must be refreshed.
    """

    token: str = pydantic.Field()
    """
    The signed JWT access token string to include in API request Authorization headers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
