# This file was auto-generated by Fern from our API Definition.

import typing

AccountPreferencesPreferredSettlementCurrency = typing.Union[
    typing.Literal["usd", "eur", "gbp", "cad", "aud"], typing.Any
]
