# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money


class AccountFeeRate(UniversalBaseModel):
    fixed: typing.Optional[Money] = pydantic.Field(default=None)
    """
    The amount charged per event. `null` when the fee has no fixed component.
    """

    percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    The percentage of the transaction, where `2` means 2%. `null` when the fee has no percentage component.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
