# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ad_creative_crop import AdCreativeCrop
from .ad_creative_format import AdCreativeFormat


class AdCreative(UniversalBaseModel):
    crop: typing.Optional[AdCreativeCrop] = pydantic.Field(default=None)
    """
    The saved crop window for this creative, in source image pixels. Null for the original asset or a format that has not been cropped.
    """

    format: typing.Optional[AdCreativeFormat] = pydantic.Field(default=None)
    """
    The placement variant this asset covers, or null for the original asset.
    """

    id: str = pydantic.Field()
    """
    The creative attachment's file id.
    """

    media_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The kind of asset, image or video.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    CDN url of the asset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
