# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AdGroupFrequencyCap(UniversalBaseModel):
    maximum_impressions: float = pydantic.Field()
    """
    Most times one person can be shown ads from this ad group within the window.
    """

    per_days: typing.Optional[float] = pydantic.Field(default=None)
    """
    Length of the rolling window, in days.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
