# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ad_pixel_platform import AdPixelPlatform
from .ad_pixel_status import AdPixelStatus


class AdPixel(UniversalBaseModel):
    account_id: str = pydantic.Field()
    """
    The business whose claimed campaigns send conversions to this pixel, prefixed `biz_`.
    """

    created_at: str = pydantic.Field()
    """
    When the pixel was added, as an ISO 8601 timestamp.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the ad platform rejected the last delivery. Null unless `status` is `errored`.
    """

    external_id: str = pydantic.Field()
    """
    The pixel's ID on the ad platform.
    """

    id: str = pydantic.Field()
    """
    Ad pixel ID, prefixed `adpx_`.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The pixel's name on the ad platform. Null when the ad platform returned none.
    """

    platform: AdPixelPlatform = pydantic.Field()
    """
    The ad platform the pixel belongs to.
    """

    status: AdPixelStatus = pydantic.Field()
    """
    `active` receives conversions. `errored` stopped because the ad platform rejected the access token; update the token to resume. `disabled` was turned off by Whop.
    """

    updated_at: str = pydantic.Field()
    """
    When the pixel was last changed, as an ISO 8601 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
