# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .app_deployment_phase import AppDeploymentPhase
from .app_deployment_status import AppDeploymentStatus


class AppDeployment(UniversalBaseModel):
    app_id: str = pydantic.Field()
    """
    The app being deployed, prefixed `app_`.
    """

    build_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The build the deployment produced, prefixed `abld_`, or `null` until it succeeds.
    """

    draft: bool = pydantic.Field()
    """
    Whether the running or last deployment uploaded a build without making it live.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the deployment failed, or `null` when it did not.
    """

    estimated_duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    How long this deployment is expected to take in total, estimated from previous runs.
    """

    estimated_remaining_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    How much longer the deployment is expected to take. Held above zero until it actually finishes.
    """

    finished_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    When the deployment ended, in milliseconds since the epoch, or `null` while it is still running.
    """

    phase: typing.Optional[AppDeploymentPhase] = pydantic.Field(default=None)
    """
    The stage a running deployment has reached, or `null` when none is running. Later phases dominate the wall clock: `process_archive` waits on the upload pipeline and `promote` waits for the build to go live.
    """

    progress: typing.Optional[float] = pydantic.Field(default=None)
    """
    Fraction of the deployment estimated to be complete, from 0 to 1. Stops just short of 1 until the run ends.
    """

    started_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    When the deployment began, in milliseconds since the epoch, or `null` when none has run.
    """

    status: AppDeploymentStatus = pydantic.Field()
    """
    Whether the app has anything to publish, and what a publish in flight is doing. `unpublished` means publishing would ship something new; `no_source` means the sandbox holds no copy of this app, so there is nothing to publish from.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Where the deployed site is served, or `null` unless the deployment went live.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
