# This file was auto-generated by Fern from our API Definition.

import typing

AppOrder = typing.Union[
    typing.Literal[
        "created_at",
        "discoverable_at",
        "total_installs_last_30_days",
        "total_installs_last_7_days",
        "time_spent",
        "time_spent_last_24_hours",
        "daily_active_users",
        "ai_prompt_count",
        "total_ai_cost_usd",
        "total_ai_tokens",
        "last_ai_prompt_at",
        "ai_average_rating",
    ],
    typing.Any,
]
