# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money


class CheckoutSessionBreakdownUpcomingRecurring(UniversalBaseModel):
    amount: Money = pydantic.Field()
    """
    What the NEXT charge takes, priced as its receipt will be: the renewal for the quantity, the buyer service fee it carries, and the promo applied only when its duration still covers that charge — a `forever` code discounts every cycle, a `once` or `repeating` one only the paying charges it has left. Stated before tax.
    """

    charge_at: str = pydantic.Field()
    """
    When the NEXT charge happens — a trial's end, a transfer's inherited period end, or the next cycle — as an ISO 8601 timestamp.
    """

    description: str = pydantic.Field()
    """
    What to show the buyer for this future charge.
    """

    interval_days: int = pydantic.Field()
    """
    Days between charges.
    """

    post_promo_amount: typing.Optional[Money] = pydantic.Field(default=None)
    """
    What each charge takes once the applied promo stops covering renewals — the steady price the subscription returns to, priced like `amount` (quantity, buyer fee, before tax). Present only when `amount` is discounted by a promo that expires (a `once` code covering the first real charge, or a `repeating` window the schedule outlives — `promo.duration` says which). Absent when no promo discounts the next charge, and for a `forever` code, whose discount never ends.
    """

    trial_days: typing.Optional[int] = pydantic.Field(default=None)
    """
    Free-trial days before the first charge. Absent when billing starts with this purchase — and on a membership transfer, which inherits the origin's clock and never re-trials.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
