# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_session_await_claim_action_state import CheckoutSessionAwaitClaimActionState


class CheckoutSessionAwaitClaimAction(UniversalBaseModel):
    blocking: bool = pydantic.Field()
    """
    Whether the sale depends on this. `true` stops the purchase until it is done — confirm refuses regardless of whether you ran it, so skipping it only costs the buyer an unexplained refusal. `false` is advisory: the purchase is already made and it stands whether or not the buyer ever does this, so the buyer may close the tab.
    """

    state: CheckoutSessionAwaitClaimActionState = pydantic.Field()
    """
    `check_email` — the claim is not recorded yet: tell the buyer to check their email to claim their purchase. `handed_off` — the claim is recorded and the checkout finished on another device: this reader keeps seeing it, which is correct — the session never unlocks across devices.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
