# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["CompanyCreateParams", "Logo"]


class CompanyCreateParams(TypedDict, total=False):
    title: Required[str]
    """The display name of the company shown to customers."""

    country: Optional[
        Literal[
            "us",
            "ca",
            "gb",
            "ab",
            "af",
            "al",
            "dz",
            "as",
            "ad",
            "ao",
            "ai",
            "aq",
            "ag",
            "ar",
            "am",
            "aw",
            "au",
            "at",
            "az",
            "bs",
            "bh",
            "bd",
            "bb",
            "by",
            "be",
            "bz",
            "bj",
            "bm",
            "bt",
            "bo",
            "ba",
            "bw",
            "br",
            "io",
            "vg",
            "bn",
            "bg",
            "bf",
            "bi",
            "kh",
            "cm",
            "cv",
            "ky",
            "cf",
            "td",
            "cl",
            "cn",
            "cx",
            "cc",
            "co",
            "km",
            "cg",
            "ck",
            "cr",
            "ci",
            "hr",
            "cu",
            "cw",
            "cy",
            "cz",
            "cd",
            "dk",
            "dj",
            "dm",
            "do",
            "ec",
            "eg",
            "sv",
            "gq",
            "ee",
            "et",
            "fk",
            "fo",
            "fj",
            "fi",
            "fr",
            "gf",
            "pf",
            "ga",
            "gm",
            "ge",
            "de",
            "gh",
            "gi",
            "gr",
            "gl",
            "gd",
            "gp",
            "gu",
            "gt",
            "gg",
            "gn",
            "gw",
            "gy",
            "ht",
            "hn",
            "hk",
            "hu",
            "is",
            "in",
            "id",
            "iq",
            "ie",
            "im",
            "il",
            "it",
            "jm",
            "sj",
            "jp",
            "je",
            "jo",
            "kz",
            "ke",
            "ki",
            "xk",
            "kw",
            "kg",
            "la",
            "lv",
            "lb",
            "ls",
            "lr",
            "ly",
            "li",
            "lt",
            "lu",
            "mo",
            "mk",
            "mg",
            "mw",
            "my",
            "mv",
            "ml",
            "mt",
            "mh",
            "mq",
            "mr",
            "mu",
            "yt",
            "mx",
            "fm",
            "md",
            "mc",
            "mn",
            "me",
            "ms",
            "ma",
            "mz",
            "mm",
            "na",
            "nr",
            "np",
            "nl",
            "an",
            "nc",
            "nz",
            "ni",
            "ne",
            "ng",
            "nu",
            "mp",
            "no",
            "om",
            "pk",
            "pw",
            "ps",
            "pa",
            "pg",
            "py",
            "pe",
            "ph",
            "pn",
            "pl",
            "pt",
            "pr",
            "qa",
            "re",
            "ro",
            "ru",
            "rw",
            "bl",
            "sh",
            "kn",
            "lc",
            "mf",
            "pm",
            "vc",
            "ws",
            "sm",
            "st",
            "sa",
            "sn",
            "rs",
            "sc",
            "sl",
            "sg",
            "sx",
            "sk",
            "si",
            "sb",
            "so",
            "za",
            "kr",
            "ss",
            "es",
            "lk",
            "sd",
            "sr",
            "sz",
            "se",
            "ch",
            "tw",
            "tj",
            "tz",
            "th",
            "tl",
            "tg",
            "tk",
            "to",
            "tt",
            "tn",
            "tr",
            "tm",
            "tc",
            "tv",
            "vi",
            "ug",
            "ua",
            "ae",
            "um",
            "uy",
            "uz",
            "vu",
            "va",
            "ve",
            "vn",
            "wf",
            "eh",
            "ye",
            "zm",
            "zw",
            "sy",
        ]
    ]
    """The available countries on the platform"""

    description: Optional[str]
    """
    A promotional pitch displayed to potential customers on the company's store
    page.
    """

    email: Optional[str]
    """The email address of the user who will own the connected account.

    Required when parent_company_id is provided.
    """

    logo: Optional[Logo]
    """The company's logo image. Accepts PNG, JPEG, or GIF format."""

    metadata: Optional[Dict[str, object]]
    """A key-value JSON object of custom metadata to store on the company."""

    parent_company_id: Optional[str]
    """The unique identifier of the parent platform company.

    When provided, creates a connected account under that platform. Omit to create a
    company for the current user.
    """

    send_customer_emails: Optional[bool]
    """Whether Whop sends transactional emails to customers on behalf of this company.

    Only applies when creating a connected account.
    """


class Logo(TypedDict, total=False):
    """The company's logo image. Accepts PNG, JPEG, or GIF format."""

    id: Required[str]
    """The ID of an existing file object."""
