# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CourseChaptersItemLessonsItemVideoAsset(UniversalBaseModel):
    """
    The Mux video asset for video-type lessons, used for streaming playback. Null if this lesson has no hosted video.
    """

    duration_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    The duration of the video in seconds
    """

    signed_playback_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed playback ID of the Mux asset
    """

    signed_thumbnail_playback_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed thumbnail playback token of the Mux asset
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
