# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mux_asset_statuses import MuxAssetStatuses


class CourseLessonVideoAsset(UniversalBaseModel):
    """
    The Mux video asset for video-type lessons, used for streaming playback. Null if this lesson has no hosted video.
    """

    asset_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Mux-provided ID of the asset
    """

    audio_only: bool = pydantic.Field()
    """
    Whether this asset contains only audio
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The datetime the mux asset was created.
    """

    duration_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    The duration of the video in seconds
    """

    finished_uploading_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The time at which the video finished uploading
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the mux asset.
    """

    playback_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The public playback ID of the Mux asset
    """

    signed_playback_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed playback ID of the Mux asset
    """

    signed_storyboard_playback_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed storyboard playback token of the Mux asset
    """

    signed_thumbnail_playback_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed thumbnail playback token of the Mux asset
    """

    signed_video_playback_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signed video playback token of the Mux asset
    """

    status: MuxAssetStatuses = pydantic.Field()
    """
    The status of the Mux asset
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The datetime the mux asset was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
