# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_reasons import BillingReasons
from .card_brands import CardBrands
from .currencies import Currencies
from .dispute_legacy_payment_member import DisputeLegacyPaymentMember
from .dispute_legacy_payment_membership import DisputeLegacyPaymentMembership
from .dispute_legacy_payment_payment_instrument import DisputeLegacyPaymentPaymentInstrument
from .dispute_legacy_payment_user import DisputeLegacyPaymentUser
from .payment_method_types import PaymentMethodTypes


class DisputeLegacyPayment(UniversalBaseModel):
    """
    The original payment that was disputed.
    """

    billing_reason: typing.Optional[BillingReasons] = pydantic.Field(default=None)
    """
    The machine-readable reason this charge was created, such as initial subscription purchase, renewal cycle, or one-time payment.
    """

    card_brand: typing.Optional[CardBrands] = pydantic.Field(default=None)
    """
    Card network reported by the processor (e.g., 'visa', 'mastercard', 'amex'). Present only when the payment method type is 'card'.
    """

    card_last4: typing.Optional[str] = pydantic.Field(default=None)
    """
    The last four digits of the card used to make this payment. Null if the payment was not made with a card.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The datetime the payment was created.
    """

    currency: Currencies = pydantic.Field()
    """
    The three-letter ISO currency code for this payment (e.g., 'usd', 'eur').
    """

    dispute_alerted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When an alert came in that this transaction will be disputed
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the payment.
    """

    member: typing.Optional[DisputeLegacyPaymentMember] = pydantic.Field(default=None)
    """
    The member attached to this payment.
    """

    membership: typing.Optional[DisputeLegacyPaymentMembership] = pydantic.Field(default=None)
    """
    The membership attached to this payment.
    """

    paid_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The time at which this payment was successfully collected. Null if the payment has not yet succeeded. As a Unix timestamp.
    """

    payment_instrument: typing.Optional[DisputeLegacyPaymentPaymentInstrument] = pydantic.Field(default=None)
    """
    The instrument this payment was made with, shaped for display: the method type, a buyer-facing name, the standard icon set, and the card facts when it was a card. Null when the receipt names no payment method.
    """

    payment_method_type: typing.Optional[PaymentMethodTypes] = pydantic.Field(default=None)
    """
    The type of payment instrument used for this payment (e.g., card, Cash App, iDEAL, Klarna, crypto). Null when the processor does not supply a type.
    """

    subtotal: typing.Optional[float] = pydantic.Field(default=None)
    """
    The subtotal to show to the creator (excluding buyer fees).
    """

    total: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total to show to the creator (excluding buyer fees).
    """

    usd_total: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total in USD to show to the creator (excluding buyer fees).
    """

    user: typing.Optional[DisputeLegacyPaymentUser] = pydantic.Field(default=None)
    """
    The user that made this payment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
