# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .currencies import Currencies
from .dispute_legacy_cancellation_policy_attachment import DisputeLegacyCancellationPolicyAttachment
from .dispute_legacy_company import DisputeLegacyCompany
from .dispute_legacy_customer_communication_attachment import DisputeLegacyCustomerCommunicationAttachment
from .dispute_legacy_payment import DisputeLegacyPayment
from .dispute_legacy_plan import DisputeLegacyPlan
from .dispute_legacy_product import DisputeLegacyProduct
from .dispute_legacy_refund_policy_attachment import DisputeLegacyRefundPolicyAttachment
from .dispute_legacy_uncategorized_attachment import DisputeLegacyUncategorizedAttachment
from .dispute_statuses import DisputeStatuses


class DisputeLegacy(UniversalBaseModel):
    """
    A dispute is a chargeback or payment challenge filed against a company, including evidence and response status.
    """

    access_activity_log: typing.Optional[str] = pydantic.Field(default=None)
    """
    A log of IP-based access activity for the customer on Whop, submitted as evidence in the dispute.
    """

    amount: float = pydantic.Field()
    """
    The disputed amount in the specified currency, formatted as a decimal.
    """

    billing_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The customer's billing address from their payment details, submitted as evidence in the dispute.
    """

    cancellation_policy_attachment: typing.Optional[DisputeLegacyCancellationPolicyAttachment] = pydantic.Field(
        default=None
    )
    """
    The cancellation policy document uploaded as dispute evidence. Null if no cancellation policy has been provided.
    """

    cancellation_policy_disclosure: typing.Optional[str] = pydantic.Field(default=None)
    """
    A text disclosure describing the company's cancellation policy, submitted as dispute evidence.
    """

    company: typing.Optional[DisputeLegacyCompany] = pydantic.Field(default=None)
    """
    The company that the dispute was filed against.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The datetime the dispute was created.
    """

    currency: Currencies = pydantic.Field()
    """
    The three-letter ISO currency code for the disputed amount.
    """

    customer_communication_attachment: typing.Optional[DisputeLegacyCustomerCommunicationAttachment] = pydantic.Field(
        default=None
    )
    """
    Evidence of customer communication or product usage, uploaded as a dispute attachment. Null if not provided.
    """

    customer_email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The customer's email address from their payment details, included in the evidence packet sent to the payment processor. Editable before submission.
    """

    customer_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The customer's full name from their payment details, included in the evidence packet sent to the payment processor. Editable before submission.
    """

    editable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the dispute evidence can still be edited and submitted.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the dispute.
    """

    needs_response_by: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The deadline by which dispute evidence must be submitted. Null if no response deadline is set.
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional freeform notes submitted by the company as part of the dispute evidence.
    """

    payment: typing.Optional[DisputeLegacyPayment] = pydantic.Field(default=None)
    """
    The original payment that was disputed.
    """

    plan: typing.Optional[DisputeLegacyPlan] = pydantic.Field(default=None)
    """
    The plan associated with the disputed payment. Null if the dispute is not linked to a specific plan.
    """

    product: typing.Optional[DisputeLegacyProduct] = pydantic.Field(default=None)
    """
    The product associated with the disputed payment. Null if the dispute is not linked to a specific product.
    """

    product_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A description of the product or service provided, submitted as dispute evidence.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable reason for the dispute.
    """

    reason_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The card network reason code for the dispute. Null when the payment processor did not provide one.
    """

    refund_policy_attachment: typing.Optional[DisputeLegacyRefundPolicyAttachment] = pydantic.Field(default=None)
    """
    The refund policy document uploaded as dispute evidence. Null if no refund policy has been provided.
    """

    refund_policy_disclosure: typing.Optional[str] = pydantic.Field(default=None)
    """
    A text disclosure describing the company's refund policy, submitted as dispute evidence.
    """

    refund_refusal_explanation: typing.Optional[str] = pydantic.Field(default=None)
    """
    An explanation from the company for why a refund was refused, submitted as dispute evidence.
    """

    service_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    The date when the product or service was delivered to the customer, submitted as dispute evidence.
    """

    status: DisputeStatuses = pydantic.Field()
    """
    The current status of the dispute lifecycle, such as needs_response, under_review, won, or lost.
    """

    uncategorized_attachment: typing.Optional[DisputeLegacyUncategorizedAttachment] = pydantic.Field(default=None)
    """
    An additional attachment that does not fit into the standard evidence categories. Null if not provided.
    """

    visa_rdr: bool = pydantic.Field()
    """
    Whether the dispute was automatically resolved through Visa Rapid Dispute Resolution (RDR).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
