# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_issue_code import DomainIssueCode


class DomainIssue(UniversalBaseModel):
    code: DomainIssueCode = pydantic.Field()
    """
    What needs attention, as a stable code.
    """

    message: str = pydantic.Field()
    """
    What needs attention before the domain can serve its app or renew.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
