# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_dns_record import DomainDnsRecord
from .domain_issue import DomainIssue
from .domain_list_item_dns_status import DomainListItemDnsStatus
from .domain_list_item_status import DomainListItemStatus
from .domain_registration_quote import DomainRegistrationQuote


class DomainListItem(UniversalBaseModel):
    account_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the account claiming or owning this domain, prefixed `biz_`. `null` for a search result.
    """

    app_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the app assigned to this domain, prefixed `app_`. `null` for a search result.
    """

    certificate_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The latest issuance status of the domain's TLS certificate.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the domain claim was created, as an ISO 8601 timestamp. `null` for a search result.
    """

    dns_records: typing.List[DomainDnsRecord]
    dns_status: typing.Optional[DomainListItemDnsStatus] = pydantic.Field(default=None)
    """
    Result of the most recent DNS routing check. Ownership is verified separately. `null` for a search result.
    """

    domain: str = pydantic.Field()
    """
    Normalized hostname, such as checkout.example.com.
    """

    hostname_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The latest activation status of the hostname on Whop's network.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Domain ID, prefixed `dom_`. `null` for a search result.
    """

    issues: typing.List[DomainIssue]
    last_checked_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When DNS and provider state were last checked, as an ISO 8601 timestamp.
    """

    metadata: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Custom string keys and values attached to this domain. Empty for a search result.
    """

    registration_quote: typing.Optional[DomainRegistrationQuote] = pydantic.Field(default=None)
    """
    Whether you can register the domain and what it costs. Set for search results and hostname lookups; `null` for your own domains.
    """

    status: typing.Optional[DomainListItemStatus] = pydantic.Field(default=None)
    """
    Domain lifecycle. Only active domains resolve to their app. `null` for a search result.
    """

    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the domain was last updated, as an ISO 8601 timestamp. `null` for a search result.
    """

    verification_expires_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When an unverified claim is automatically deleted, 48 hours after creation, as an ISO 8601 timestamp.
    """

    verified_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When Whop verified the ownership TXT record, as an ISO 8601 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
