# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExperienceProductsItem(UniversalBaseModel):
    """
    A product is a digital good or service sold on Whop. Products contain plans for pricing and experiences for content delivery.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the product.
    """

    route: str = pydantic.Field()
    """
    URL slug in the product's public link, e.g. `pickaxe-analytics` in whop.com/company/pickaxe-analytics.
    """

    title: str = pydantic.Field()
    """
    The display name of the product shown to customers on the product page and in search results.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
