# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .notification_experience_app import NotificationExperienceApp


class NotificationExperience(UniversalBaseModel):
    app: typing.Optional[NotificationExperienceApp] = pydantic.Field(default=None)
    """
    App the experience belongs to.
    """

    id: str = pydantic.Field()
    """
    Experience ID, prefixed `exp_`.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the experience.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
