# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Pagination(UniversalBaseModel):
    current_page: float = pydantic.Field()
    """
    Current page number
    """

    next_page: typing.Optional[float] = pydantic.Field(default=None)
    """
    Next page number
    """

    prev_page: typing.Optional[float] = pydantic.Field(default=None)
    """
    Previous page number
    """

    total_count: float = pydantic.Field()
    """
    Total number of records
    """

    total_pages: float = pydantic.Field()
    """
    Total number of pages
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
