# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_input_line_items_item import PaymentInputLineItemsItem
from .payment_input_plan import PaymentInputPlan


class PaymentInput(UniversalBaseModel):
    """
    The purchase: the account it belongs to, what is bought, and the promo code applied. The same shape prices a purchase and pays for it.
    """

    account_id: str = pydantic.Field()
    """
    The account the purchase belongs to, prefixed `biz_`.
    """

    line_items: typing.Optional[typing.List[PaymentInputLineItemsItem]] = pydantic.Field(default=None)
    """
    What the buyer is purchasing. One entry charges that variant; several entries form a cart, which requires every variant to be compatible, belong to this account, and use the same currency.
    """

    plan: typing.Optional[PaymentInputPlan] = pydantic.Field(default=None)
    """
    The variant purchased, described by its attributes instead of an id: the variant with exactly these attributes is used, and one is created when none exists. Mutually exclusive with `plan_id` and `line_items`. Creating a variant requires `plan:create`; creating or updating a product requires the corresponding product permission.
    """

    plan_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The variant purchased, prefixed `plan_`. It must belong to the account. Mutually exclusive with `plan` and `line_items`.
    """

    promo_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The promo code as the buyer typed it, matched within the account regardless of case and surrounding spaces, as checkout matches it. It must be valid for the variant. Send it or `promo_code_id`, not both; an empty or whitespace-only string counts as not sent. A code the account does not have, or one that is no longer active, is refused before anything is written, with the error code `promo_invalid`.
    """

    promo_code_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An active promo code to apply, prefixed `promo_`. It must belong to the account and be valid for the variant. Send it or `promo_code`, not both.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
