# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PaymentMethodIconFiles(UniversalBaseModel):
    png1x: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="png_1x"),
        pydantic.Field(alias="png_1x", description="Raster fallback at the shape's native size."),
    ]
    """
    Raster fallback at the shape's native size.
    """

    png2x: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="png_2x"),
        pydantic.Field(alias="png_2x", description="Raster fallback at double density."),
    ]
    """
    Raster fallback at double density.
    """

    png4x: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="png_4x"),
        pydantic.Field(alias="png_4x", description="Raster fallback at quadruple density."),
    ]
    """
    Raster fallback at quadruple density.
    """

    svg: str = pydantic.Field()
    """
    The vector file. Prefer this everywhere SVG renders.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
