# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_method_cashapp_payment_method_icons_square_dark import PaymentMethodCashappPaymentMethodIconsSquareDark
from .payment_method_cashapp_payment_method_icons_square_light import PaymentMethodCashappPaymentMethodIconsSquareLight


class PaymentMethodCashappPaymentMethodIconsSquare(UniversalBaseModel):
    """
    The square tile (32x32).
    """

    dark: PaymentMethodCashappPaymentMethodIconsSquareDark = pydantic.Field()
    """
    The colorway for dark surfaces.
    """

    light: PaymentMethodCashappPaymentMethodIconsSquareLight = pydantic.Field()
    """
    The colorway for light surfaces.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
