# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_method_list_item_base_payment_method_icons import PaymentMethodListItemBasePaymentMethodIcons
from .payment_method_list_item_card_payment_method_card import PaymentMethodListItemCardPaymentMethodCard
from .payment_method_list_item_card_payment_method_icons import PaymentMethodListItemCardPaymentMethodIcons
from .payment_method_list_item_cashapp_payment_method_cashapp import PaymentMethodListItemCashappPaymentMethodCashapp
from .payment_method_list_item_cashapp_payment_method_icons import PaymentMethodListItemCashappPaymentMethodIcons
from .payment_method_list_item_ideal_payment_method_icons import PaymentMethodListItemIdealPaymentMethodIcons
from .payment_method_list_item_ideal_payment_method_ideal import PaymentMethodListItemIdealPaymentMethodIdeal
from .payment_method_list_item_sepa_debit_payment_method_icons import PaymentMethodListItemSepaDebitPaymentMethodIcons
from .payment_method_list_item_sepa_debit_payment_method_sepa_debit import (
    PaymentMethodListItemSepaDebitPaymentMethodSepaDebit,
)
from .payment_method_list_item_us_bank_account_payment_method_icons import (
    PaymentMethodListItemUsBankAccountPaymentMethodIcons,
)
from .payment_method_list_item_us_bank_account_payment_method_us_bank_account import (
    PaymentMethodListItemUsBankAccountPaymentMethodUsBankAccount,
)
from .payment_method_types import PaymentMethodTypes


class PaymentMethodListItem_BasePaymentMethod(UniversalBaseModel):
    typename: typing.Literal["BasePaymentMethod"] = "BasePaymentMethod"
    created_at: dt.datetime
    icons: PaymentMethodListItemBasePaymentMethodIcons
    id: str
    payment_method_type: PaymentMethodTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PaymentMethodListItem_CardPaymentMethod(UniversalBaseModel):
    typename: typing.Literal["CardPaymentMethod"] = "CardPaymentMethod"
    card: PaymentMethodListItemCardPaymentMethodCard
    created_at: dt.datetime
    has_payer_document: bool
    icons: PaymentMethodListItemCardPaymentMethodIcons
    id: str
    payment_method_type: PaymentMethodTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PaymentMethodListItem_UsBankAccountPaymentMethod(UniversalBaseModel):
    typename: typing.Literal["UsBankAccountPaymentMethod"] = "UsBankAccountPaymentMethod"
    created_at: dt.datetime
    icons: PaymentMethodListItemUsBankAccountPaymentMethodIcons
    id: str
    payment_method_type: PaymentMethodTypes
    us_bank_account: PaymentMethodListItemUsBankAccountPaymentMethodUsBankAccount

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PaymentMethodListItem_CashappPaymentMethod(UniversalBaseModel):
    typename: typing.Literal["CashappPaymentMethod"] = "CashappPaymentMethod"
    cashapp: PaymentMethodListItemCashappPaymentMethodCashapp
    created_at: dt.datetime
    icons: PaymentMethodListItemCashappPaymentMethodIcons
    id: str
    payment_method_type: PaymentMethodTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PaymentMethodListItem_IdealPaymentMethod(UniversalBaseModel):
    typename: typing.Literal["IdealPaymentMethod"] = "IdealPaymentMethod"
    created_at: dt.datetime
    icons: PaymentMethodListItemIdealPaymentMethodIcons
    id: str
    ideal: PaymentMethodListItemIdealPaymentMethodIdeal
    payment_method_type: PaymentMethodTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PaymentMethodListItem_SepaDebitPaymentMethod(UniversalBaseModel):
    typename: typing.Literal["SepaDebitPaymentMethod"] = "SepaDebitPaymentMethod"
    created_at: dt.datetime
    icons: PaymentMethodListItemSepaDebitPaymentMethodIcons
    id: str
    payment_method_type: PaymentMethodTypes
    sepa_debit: PaymentMethodListItemSepaDebitPaymentMethodSepaDebit

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PaymentMethodListItem = typing_extensions.Annotated[
    typing.Union[
        PaymentMethodListItem_BasePaymentMethod,
        PaymentMethodListItem_CardPaymentMethod,
        PaymentMethodListItem_UsBankAccountPaymentMethod,
        PaymentMethodListItem_CashappPaymentMethod,
        PaymentMethodListItem_IdealPaymentMethod,
        PaymentMethodListItem_SepaDebitPaymentMethod,
    ],
    pydantic.Field(discriminator="typename"),
]
