# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_legacy_payment_method_card import PaymentLegacyPaymentMethodCard
from .payment_method_types import PaymentMethodTypes


class PaymentLegacyPaymentMethod(UniversalBaseModel):
    """
    The tokenized payment method reference used for this payment. Null if no token was used.
    """

    card: typing.Optional[PaymentLegacyPaymentMethodCard] = pydantic.Field(default=None)
    """
    The card data associated with the payment method, if its a debit or credit card.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The datetime the payment token was created.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the payment token.
    """

    payment_method_type: PaymentMethodTypes = pydantic.Field()
    """
    The payment method type of the payment method
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
