# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .custom_ctas import CustomCtas
from .global_affiliate_statuses import GlobalAffiliateStatuses
from .product_legacy_company import ProductLegacyCompany
from .product_legacy_gallery_images_item import ProductLegacyGalleryImagesItem
from .product_legacy_owner_user import ProductLegacyOwnerUser
from .product_legacy_product_tax_code import ProductLegacyProductTaxCode
from .visibility import Visibility


class ProductLegacy(UniversalBaseModel):
    """
    A product is a digital good or service sold on Whop. Products contain plans for pricing and experiences for content delivery.
    """

    company: ProductLegacyCompany = pydantic.Field()
    """
    The company this product belongs to.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The datetime the product was created.
    """

    custom_cta: CustomCtas = pydantic.Field()
    """
    Call-to-action button label shown on the product purchase page.
    """

    custom_cta_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional URL that the call-to-action button links to instead of the default checkout flow. Null if no custom URL is set.
    """

    custom_statement_descriptor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom bank statement descriptor for product purchases. Maximum 22 characters, including required `WHOP*` prefix.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A brief summary of what the product offers, displayed on product pages and search results.
    """

    external_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    External identifier for the product. Providing it on a product creation endpoint updates the existing product with this identifier instead of creating a new one.
    """

    gallery_images: typing.List[ProductLegacyGalleryImagesItem] = pydantic.Field()
    """
    The gallery images for this product, ordered by position.
    """

    global_affiliate_percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    Marketplace affiliate commission percentage for this product, or `null` if program is inactive.
    """

    global_affiliate_status: GlobalAffiliateStatuses = pydantic.Field()
    """
    The enrollment status of this product in the Whop marketplace global affiliate program.
    """

    headline: typing.Optional[str] = pydantic.Field(default=None)
    """
    A short marketing headline displayed prominently on the product's product page.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the product.
    """

    member_affiliate_percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    Member referral commission percentage for this product, or `null` if program is inactive.
    """

    member_affiliate_status: GlobalAffiliateStatuses = pydantic.Field()
    """
    The enrollment status of this product in the member affiliate program.
    """

    member_count: int = pydantic.Field()
    """
    Active memberships for this product. Returns `0` if the account has disabled public member counts.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom key-value pairs stored on the product and included in payment and membership webhook payloads. Max 50 keys, 100 characters per key, 500 characters per string value.
    """

    owner_user: ProductLegacyOwnerUser = pydantic.Field()
    """
    The user who owns the company that sells this product.
    """

    product_tax_code: typing.Optional[ProductLegacyProductTaxCode] = pydantic.Field(default=None)
    """
    The tax classification code applied to purchases of this product for sales tax calculation. Null if no tax code is assigned.
    """

    published_reviews_count: int = pydantic.Field()
    """
    The total number of published customer reviews for this product's company.
    """

    route: str = pydantic.Field()
    """
    URL slug in the product's public link, e.g. `pickaxe-analytics` in whop.com/company/pickaxe-analytics.
    """

    title: str = pydantic.Field()
    """
    The display name of the product shown to customers on the product page and in search results.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The datetime the product was last updated.
    """

    verified: bool = pydantic.Field()
    """
    Whether this company has been verified by Whop's trust and safety team.
    """

    visibility: Visibility = pydantic.Field()
    """
    Controls whether the product is visible to customers. When set to 'hidden', the product is only accessible via direct link.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
