# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money
from .product_public_plan_plan_type import ProductPublicPlanPlanType
from .product_public_plan_visibility import ProductPublicPlanVisibility


class ProductPublicPlan(UniversalBaseModel):
    billing_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of days between recurring charges, such as 30 for monthly or 365 for annual. `null` for one-time variants.
    """

    expiration_days: typing.Optional[float] = pydantic.Field(default=None)
    """
    Access duration in days for expiration-based variants. `null` for variants without an expiration.
    """

    id: str = pydantic.Field()
    """
    Variant ID, prefixed `plan_`.
    """

    initial_price: Money = pydantic.Field()
    """
    What checkout charges up front. `amount` is `"0.00"` when the first charge is free, such as a trial.
    """

    plan_type: ProductPublicPlanPlanType = pydantic.Field()
    """
    Billing model for this variant: `one_time` or `renewal`.
    """

    renewal_price: Money = pydantic.Field()
    """
    The recurring charge every `billing_period` days. `amount` is `"0.00"` for one-time variants.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Variant display name shown to customers. `null` if no title has been set.
    """

    unlimited_stock: bool = pydantic.Field()
    """
    Whether the variant has unlimited stock.
    """

    visibility: ProductPublicPlanVisibility = pydantic.Field()
    """
    Where this variant can be seen. `visible` variants appear on the product page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
