# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .setup_intent_checkout_configuration import SetupIntentCheckoutConfiguration
from .setup_intent_company import SetupIntentCompany
from .setup_intent_member import SetupIntentMember
from .setup_intent_payment_method import SetupIntentPaymentMethod
from .setup_intent_statuses import SetupIntentStatuses


class SetupIntent(UniversalBaseModel):
    """
    A setup intent allows a user to save a payment method for future use without making an immediate purchase.
    """

    checkout_configuration: typing.Optional[SetupIntentCheckoutConfiguration] = pydantic.Field(default=None)
    """
    The checkout session configuration associated with this setup intent. Null if no checkout session was used.
    """

    company: typing.Optional[SetupIntentCompany] = pydantic.Field(default=None)
    """
    The company that initiated this setup intent. Null if the company has been deleted.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The datetime the setup intent was created.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable error message explaining why the setup intent failed. Null if no error occurred.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the setup intent.
    """

    member: typing.Optional[SetupIntentMember] = pydantic.Field(default=None)
    """
    The company member associated with this setup intent. Null if the user is not a member.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom key-value pairs attached to this setup intent. Null if no metadata was provided.
    """

    payment_method: typing.Optional[SetupIntentPaymentMethod] = pydantic.Field(default=None)
    """
    The saved payment method created by this setup intent. Null if the setup has not completed successfully.
    """

    status: SetupIntentStatuses = pydantic.Field()
    """
    The current status of the setup intent.
    """

    three_ds_verified: bool = pydantic.Field()
    """
    Whether 3D Secure authentication was completed when this payment method was set up.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
