# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .setup_intent_member_user import SetupIntentMemberUser


class SetupIntentMember(UniversalBaseModel):
    """
    The company member associated with this setup intent. Null if the user is not a member.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for the company member.
    """

    user: typing.Optional[SetupIntentMemberUser] = pydantic.Field(default=None)
    """
    The user for this member, if any.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
