# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["WebhookEvent"]

WebhookEvent: TypeAlias = Literal[
    "invoice.created",
    "invoice.marked_uncollectible",
    "invoice.paid",
    "invoice.past_due",
    "invoice.voided",
    "membership.activated",
    "membership.deactivated",
    "membership.trial_ending_soon",
    "entry.created",
    "entry.approved",
    "entry.denied",
    "entry.deleted",
    "setup_intent.requires_action",
    "setup_intent.succeeded",
    "setup_intent.canceled",
    "ledger_account.funds_available",
    "deposit.succeeded",
    "withdrawal.created",
    "withdrawal.updated",
    "card_transaction.created",
    "card_transaction.updated",
    "card_transaction.completed",
    "card_transaction.declined",
    "card_transaction.reversed",
    "course_lesson_interaction.completed",
    "payout_method.created",
    "verification.succeeded",
    "identity_profile.approved",
    "identity_profile.rejected",
    "identity_profile.needs_action",
    "identity_profile.updated",
    "payout_account.status_updated",
    "resolution_center_case.created",
    "resolution_center_case.updated",
    "resolution_center_case.decided",
    "product.created",
    "product.updated",
    "product.deleted",
    "product.published",
    "product.unpublished",
    "chat.message.created",
    "chat.reaction.created",
    "payment.created",
    "payment.succeeded",
    "payment.failed",
    "payment.pending",
    "dispute.created",
    "dispute.updated",
    "refund.created",
    "refund.updated",
    "dispute_alert.created",
    "membership.cancel_at_period_end_changed",
]
