# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.v1error_response import V1ErrorResponse
from .types.create_payouts_request_body import CreatePayoutsRequestBody
from .types.create_payouts_response import CreatePayoutsResponse
from .types.list_payouts_request_source import ListPayoutsRequestSource
from .types.list_payouts_request_status import ListPayoutsRequestStatus
from .types.list_payouts_response import ListPayoutsResponse
from .types.list_payouts_response_data_item import ListPayoutsResponseDataItem
from .types.retrieve_payouts_response import RetrievePayoutsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPayoutsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        account_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        currency: typing.Optional[str] = None,
        status: typing.Optional[ListPayoutsRequestStatus] = None,
        source: typing.Optional[ListPayoutsRequestSource] = None,
        payout_method_id: typing.Optional[str] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListPayoutsResponseDataItem, ListPayoutsResponse]:
        """
        Lists an account's or user's payouts, newest first.

        Parameters
        ----------
        account_id : typing.Optional[str]
            The owning account ID (a biz_ identifier). Provide this or user_id.

        user_id : typing.Optional[str]
            The owning user ID (a user_ identifier). Provide this or account_id.

        currency : typing.Optional[str]
            Optional currency code filter, for example `usd`.

        status : typing.Optional[ListPayoutsRequestStatus]
            Filter to payouts whose `status` reads this word, matching exactly what this version displays — `reversed` finds settled payouts the bank later returned. Requires Api-Version-Date 2026-08-21 or later.

        source : typing.Optional[ListPayoutsRequestSource]
            Filter by how the payout was created. Payouts created before source tracking or through internal tooling carry no source and never match.

        payout_method_id : typing.Optional[str]
            Filter to payouts sent to one saved payout method (a pytk_ identifier). An unknown id matches nothing.

        created_before : typing.Optional[dt.datetime]
            Only payouts created before this ISO 8601 time (exclusive).

        created_after : typing.Optional[dt.datetime]
            Only payouts created at or after this ISO 8601 time (inclusive).

        first : typing.Optional[int]
            Number of payouts to return from the start of the window.

        after : typing.Optional[str]
            Cursor to fetch the page after (from page_info.end_cursor).

        last : typing.Optional[int]
            Number of payouts to return from the end of the window.

        before : typing.Optional[str]
            Cursor to fetch the page before (from page_info.start_cursor).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListPayoutsResponseDataItem, ListPayoutsResponse]
            payouts filtered by source, payout method, and created window
        """
        _response = self._client_wrapper.httpx_client.request(
            "payouts",
            method="GET",
            params={
                "account_id": account_id,
                "user_id": user_id,
                "currency": currency,
                "status": status,
                "source": source,
                "payout_method_id": payout_method_id,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPayoutsResponse,
                    parse_obj_as(
                        type_=ListPayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        account_id=account_id,
                        user_id=user_id,
                        currency=currency,
                        status=status,
                        source=source,
                        payout_method_id=payout_method_id,
                        created_before=created_before,
                        created_after=created_after,
                        first=first,
                        after=_parsed_next,
                        last=last,
                        before=before,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self, *, request: CreatePayoutsRequestBody, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreatePayoutsResponse]:
        """
        Sends money from an account or user balance to a saved payout method for that owner.

        Parameters
        ----------
        request : CreatePayoutsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreatePayoutsResponse]
            payout created
        """
        _response = self._client_wrapper.httpx_client.request(
            "payouts",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreatePayoutsRequestBody, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePayoutsResponse,
                    parse_obj_as(
                        type_=CreatePayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve(
        self,
        id: str,
        *,
        account_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RetrievePayoutsResponse]:
        """
        Fetches one payout by its `wdrl_` ID, or by the `cofr_` conversion request ID a stablecoin payout carries as `payout_request_id` — both ids answer with the same payout object.

        Parameters
        ----------
        id : str
            Payout ID, prefixed `wdrl_` for a payout returned by `GET /payouts` or `cofr_` for the payout request returned by `POST /payouts`.

        account_id : typing.Optional[str]
            Owning account ID, prefixed `biz_`. Provide exactly one of `account_id` or `user_id`.

        user_id : typing.Optional[str]
            Owning user ID, prefixed `user_`. Provide exactly one of `account_id` or `user_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetrievePayoutsResponse]
            payout found for a user
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payouts/{encode_path_param(id)}",
            method="GET",
            params={
                "account_id": account_id,
                "user_id": user_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrievePayoutsResponse,
                    parse_obj_as(
                        type_=RetrievePayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPayoutsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        account_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        currency: typing.Optional[str] = None,
        status: typing.Optional[ListPayoutsRequestStatus] = None,
        source: typing.Optional[ListPayoutsRequestSource] = None,
        payout_method_id: typing.Optional[str] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        first: typing.Optional[int] = None,
        after: typing.Optional[str] = None,
        last: typing.Optional[int] = None,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListPayoutsResponseDataItem, ListPayoutsResponse]:
        """
        Lists an account's or user's payouts, newest first.

        Parameters
        ----------
        account_id : typing.Optional[str]
            The owning account ID (a biz_ identifier). Provide this or user_id.

        user_id : typing.Optional[str]
            The owning user ID (a user_ identifier). Provide this or account_id.

        currency : typing.Optional[str]
            Optional currency code filter, for example `usd`.

        status : typing.Optional[ListPayoutsRequestStatus]
            Filter to payouts whose `status` reads this word, matching exactly what this version displays — `reversed` finds settled payouts the bank later returned. Requires Api-Version-Date 2026-08-21 or later.

        source : typing.Optional[ListPayoutsRequestSource]
            Filter by how the payout was created. Payouts created before source tracking or through internal tooling carry no source and never match.

        payout_method_id : typing.Optional[str]
            Filter to payouts sent to one saved payout method (a pytk_ identifier). An unknown id matches nothing.

        created_before : typing.Optional[dt.datetime]
            Only payouts created before this ISO 8601 time (exclusive).

        created_after : typing.Optional[dt.datetime]
            Only payouts created at or after this ISO 8601 time (inclusive).

        first : typing.Optional[int]
            Number of payouts to return from the start of the window.

        after : typing.Optional[str]
            Cursor to fetch the page after (from page_info.end_cursor).

        last : typing.Optional[int]
            Number of payouts to return from the end of the window.

        before : typing.Optional[str]
            Cursor to fetch the page before (from page_info.start_cursor).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListPayoutsResponseDataItem, ListPayoutsResponse]
            payouts filtered by source, payout method, and created window
        """
        _response = await self._client_wrapper.httpx_client.request(
            "payouts",
            method="GET",
            params={
                "account_id": account_id,
                "user_id": user_id,
                "currency": currency,
                "status": status,
                "source": source,
                "payout_method_id": payout_method_id,
                "created_before": serialize_datetime(created_before) if created_before is not None else None,
                "created_after": serialize_datetime(created_after) if created_after is not None else None,
                "first": first,
                "after": after,
                "last": last,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPayoutsResponse,
                    parse_obj_as(
                        type_=ListPayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.page_info is not None:
                    _parsed_next = _parsed_response.page_info.end_cursor
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            account_id=account_id,
                            user_id=user_id,
                            currency=currency,
                            status=status,
                            source=source,
                            payout_method_id=payout_method_id,
                            created_before=created_before,
                            created_after=created_after,
                            first=first,
                            after=_parsed_next,
                            last=last,
                            before=before,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self, *, request: CreatePayoutsRequestBody, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreatePayoutsResponse]:
        """
        Sends money from an account or user balance to a saved payout method for that owner.

        Parameters
        ----------
        request : CreatePayoutsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreatePayoutsResponse]
            payout created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "payouts",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreatePayoutsRequestBody, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePayoutsResponse,
                    parse_obj_as(
                        type_=CreatePayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        V1ErrorResponse,
                        parse_obj_as(
                            type_=V1ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve(
        self,
        id: str,
        *,
        account_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RetrievePayoutsResponse]:
        """
        Fetches one payout by its `wdrl_` ID, or by the `cofr_` conversion request ID a stablecoin payout carries as `payout_request_id` — both ids answer with the same payout object.

        Parameters
        ----------
        id : str
            Payout ID, prefixed `wdrl_` for a payout returned by `GET /payouts` or `cofr_` for the payout request returned by `POST /payouts`.

        account_id : typing.Optional[str]
            Owning account ID, prefixed `biz_`. Provide exactly one of `account_id` or `user_id`.

        user_id : typing.Optional[str]
            Owning user ID, prefixed `user_`. Provide exactly one of `account_id` or `user_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetrievePayoutsResponse]
            payout found for a user
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payouts/{encode_path_param(id)}",
            method="GET",
            params={
                "account_id": account_id,
                "user_id": user_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrievePayoutsResponse,
                    parse_obj_as(
                        type_=RetrievePayoutsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
