# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_trades_request_orders_item_order_type import CreateTradesRequestOrdersItemOrderType
from .create_trades_request_orders_item_side import CreateTradesRequestOrdersItemSide
from .create_trades_request_orders_item_stop_loss import CreateTradesRequestOrdersItemStopLoss
from .create_trades_request_orders_item_take_profit import CreateTradesRequestOrdersItemTakeProfit
from .create_trades_request_orders_item_time_in_force import CreateTradesRequestOrdersItemTimeInForce


class CreateTradesRequestOrdersItem(UniversalBaseModel):
    market: str = pydantic.Field()
    """
    Perpetual market on the selected provider, such as `ETH`.
    """

    order_type: typing.Optional[CreateTradesRequestOrdersItemOrderType] = None
    price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Limit price as a decimal string. Required for a limit order; for a take-profit or stop-loss, omit it to trigger a market order.
    """

    reduce_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the order can only reduce an existing position. Take-profit and stop-loss orders are always reduce-only.
    """

    side: CreateTradesRequestOrdersItemSide
    size: str = pydantic.Field()
    """
    Order size as a decimal string.
    """

    slippage_bps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Slippage cap for this order in basis points, overriding the request's `slippage_bps`.
    """

    stop_loss: typing.Optional[CreateTradesRequestOrdersItemStopLoss] = pydantic.Field(default=None)
    """
    Stop-loss to attach to a single entry order.
    """

    take_profit: typing.Optional[CreateTradesRequestOrdersItemTakeProfit] = pydantic.Field(default=None)
    """
    Take-profit to attach to a single entry order.
    """

    time_in_force: typing.Optional[CreateTradesRequestOrdersItemTimeInForce] = pydantic.Field(default=None)
    """
    How long a limit order stays active. Ignored for other order types.
    """

    trigger_price: typing.Optional[str] = pydantic.Field(default=None)
    """
    Trigger price as a decimal string. Required for standalone take-profit and stop-loss orders.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
